import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const src=fs.readFileSync(new URL('../lib/store.ts',import.meta.url),'utf8');
const extract=(name,next)=>src.slice(src.indexOf('export function '+name),src.indexOf(next,src.indexOf('export function '+name))).replace('export ','');
// Exercise the same profile validation and mutation branch without database or OAuth.
const checkedPhoto=new Function('value',src.slice(src.indexOf('function checkedPhoto(value:unknown){')+'function checkedPhoto(value:unknown){'.length,src.indexOf('\nfunction required')) .slice(0,-1));
const nameBody=src.slice(src.indexOf('function checkedInstituteName(value:unknown,allowEmpty=false){')+'function checkedInstituteName(value:unknown,allowEmpty=false){'.length,src.indexOf('\nfunction change')).slice(0,-1);
const checkedInstituteName=new Function('value','allowEmpty',nameBody);
const profileBranch=src.slice(src.indexOf("if(method==='PATCH'&&resource==='profile'){"),src.indexOf('const now=new Date().toISOString();',src.indexOf('function change')));
const patch=new Function('s','b','checkedPhoto','checkedInstituteName',"const method='PATCH',resource='profile';"+profileBranch);
test('coaching profile edits preserve photo and photo changes preserve coaching name',()=>{const s={profile:{photo:'',instituteName:'First Coaching'}};patch(s,{instituteName:' New Coaching '},checkedPhoto,checkedInstituteName);assert.equal(s.profile.instituteName,'New Coaching');patch(s,{photo:''},checkedPhoto,checkedInstituteName);assert.equal(s.profile.instituteName,'New Coaching');for(const name of ['', ' '.repeat(4), 'a'.repeat(121),'Name\nFake'])assert.throws(()=>patch(s,{instituteName:name},checkedPhoto,checkedInstituteName));});
test('receipt name is tenant-specific and no longer uses shared demo environment',()=>{const r=src.slice(src.indexOf('export function receipt('),src.indexOf('export async function access'));assert.match(r,/s\.profile\?\.instituteName/);assert.doesNotMatch(r,/process\.env\.INSTITUTE_NAME|ABC Coaching/);assert.match(src,/instituteName:x\.profile\?\.instituteName/)});
test('customer portal first-use resolves tenant before querying plans',()=>{const portal=fs.readFileSync(new URL('../app/api/customer-portal/route.ts',import.meta.url),'utf8');assert.match(portal,/await readStore\(a,false\);return a/);const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');assert.match(ui,/if\(v.entitlement\?\.active!==false\)await refresh\(\);else setPage\('Plans \/ Purchase'\);\s*if\(active\)await loadCustomerPortal/);assert.match(ui,/Retry plans/)});
test('pending reminder uses tenant coaching name and fallback, never shared demo name',()=>{const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');const reminder=ui.slice(ui.indexOf('function sendReminder'),ui.indexOf('async function openWhatsApp'));assert.match(reminder,/instituteName\.trim\(\)\|\|'Your Coaching'/);assert.doesNotMatch(reminder,/ABC Coaching/)});
test('pending mobile records have labels, and all modal overlays lock scrolling',()=>{const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../app/style.css',import.meta.url),'utf8');assert.match(ui,/pending-fees-panel/);for(const label of ['Pending','Due date','Actions'])assert.ok(ui.includes('data-label={tr("'+label+'")}'));assert.match(ui,/!trialPaymentPrompt&&!modal&&!deleteTarget&&!paymentTarget&&!planEdit/);assert.match(css,/box-shadow:0 0 0 100vmax #0d1c19a8/);assert.match(css,/\.pending-fees-panel thead\{display:none\}/)});
test('multi-batch fee rows show fee batch, all confirmation dialogs lock scroll and print removes backdrop',()=>{const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../app/style.css',import.meta.url),'utf8');assert.ok(ui.includes('data-label={tr("Batch")}>{f.batch?.name||f.student.batch?.name}'));assert.match(ui,/!planEdit&&!statusTarget&&!purchaseChoice/);assert.match(css,/@media print\{\.overlay\{box-shadow:none!important/)});
test('customer reports cannot render empty initial arrays before the first refresh',()=>{const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');assert.match(ui,/workspaceLoaded,setWorkspaceLoaded/);assert.match(ui,/setWorkspaceLoaded\(true\)/);assert.match(ui,/!owner&&!workspaceLoaded&&plan\?\.entitlement\?\.active!==false/);assert.match(ui,/Retry loading data/)});
test('small dialog action footers wrap instead of hiding Cancel',()=>{const css=fs.readFileSync(new URL('../app/style.css',import.meta.url),'utf8');assert.match(css,/\.dialog \.form-actions\{flex-wrap:wrap\}/);assert.match(css,/\.dialog \.form-actions button\{max-width:100%;white-space:normal/)});
test('tablet workspace reserves width for sidebar and avoids dashboard/header overflow',()=>{const css=fs.readFileSync(new URL('../app/style.css',import.meta.url),'utf8');assert.match(css,/@media\(min-width:701px\) and \(max-width:1100px\)/);assert.match(css,/\.app \.metrics\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)\}/);assert.match(css,/\.app \.breadcrumb,\.app \.admin-label,\.app \.admin-identity\{display:none\}/)});
test('tablet owner metric grid fits without overflowing four columns',()=>{const css=fs.readFileSync(new URL('../app/style.css',import.meta.url),'utf8');assert.match(css,/\.admin-metrics\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)\}/);assert.match(css,/\.admin-stat strong\{font-size:28px;overflow-wrap:anywhere\}/)});
test('terms match the three-day trial and manually verified 299 Store term',()=>{const terms=fs.readFileSync(new URL('../app/terms/page.tsx',import.meta.url),'utf8');assert.match(terms,/free 3-day trial/);assert.match(terms,/₹299 for each 30-day term/);assert.match(terms,/does not renew or charge automatically/);assert.doesNotMatch(terms,/No paid subscription/)});
test('Hindi backup and support cover restore review, trial banner and user confirmation',()=>{const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');for(const word of ['उत्पाद सहायता','विषय','विवरण','बैकअप फाइल 18 MB से बड़ी है','रिकॉर्ड बदलने की पुष्टि','वापस लाए जाएंगे','आपका ट्रायल समाप्त होगा'])assert.ok(ui.includes(word));assert.ok(ui.includes('aria-label={tr("Choose backup JSON")}'));assert.ok(ui.includes('setNotice(tr(\'Issue sent to product support.\'))'))});
test('student avatar options replace uploads while preserving existing photos',async()=>{const {checkedStudentAvatar,studentPhotoForSave}=await import('../lib/student-avatar.ts');assert.equal(checkedStudentAvatar('female'),'female');assert.equal(checkedStudentAvatar(undefined),'male');assert.throws(()=>checkedStudentAvatar('other'));assert.equal(studentPhotoForSave(undefined,'legacy-image'),'legacy-image');assert.equal(studentPhotoForSave('legacy-image','legacy-image'),'legacy-image');assert.throws(()=>studentPhotoForSave('new-image','legacy-image'));assert.equal(studentPhotoForSave(''),'');const ui=fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');assert.match(ui,/student-avatar-picker/);assert.doesNotMatch(ui,/Student photo \(optional\).*?<input type="file"/);});

test('attendance exports keep unmarked separate and deduplicate per batch day',async()=>{const {attendanceReportRows}=await import('../lib/attendance-report.ts');const students=[{id:'s',studentId:'T1',name:'Test',batchIds:['b']}],marks=[{studentId:'s',batchId:'b',date:'2026-09-01',status:'Present'},{studentId:'s',batchId:'b',date:'2026-09-01',status:'Present'},{studentId:'s',batchId:'b',date:'2026-09-02',status:'Absent'},{studentId:'s',batchId:'foreign',date:'2026-09-03',status:'Absent'}];const [r]=attendanceReportRows(students,marks,'b','2026-09',true);assert.equal(r.present,1);assert.equal(r.absent,1);assert.equal(r.unmarked,28);assert.equal(r.rate,50);assert.equal(attendanceReportRows(students,marks,'b','2026-09-03')[0].status,'Not marked');assert.throws(()=>attendanceReportRows(students,marks,'','2026-09',true));});
