import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
const root='http://127.0.0.1:3213',server=spawn('./node_modules/.bin/next',['start','-p','3213'],{env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:'ignore'});
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});
let data={batches:[{id:'b1',name:'Evening A',courseName:'Maths',teacherName:'Anita',timing:'5 PM',monthlyFee:200000,status:'Active',_count:{students:1}}],students:[{id:'s1',studentId:'STU-01',name:'Ravi',parentName:'Neha',mobile:'9876543210',batchId:'b1',batch:{name:'Evening A'},monthlyFee:200000,joiningDate:'2026-09-01T00:00:00Z',notes:'',photo:'',status:'Active',pendingAmount:150000}],fees:[{id:'f1',studentId:'s1',student:{id:'s1',name:'Ravi',studentId:'STU-01',mobile:'9876543210',parentName:'Neha',batchId:'b1',batch:{name:'Evening A'}},month:'2026-09',totalFee:180000,baseFee:200000,discount:20000,dueDate:'2026-09-27T00:00:00Z',paidAmount:30000,pendingAmount:150000,status:'Overdue'}],payments:[{id:'p1',studentId:'s1',student:{name:'Ravi',studentId:'STU-01'},fee:{month:'2026-09'},paymentDate:'2026-09-28T00:00:00Z',amount:30000,mode:'UPI',receipt:{id:'r1',number:'REC-00001',remainingAmount:150000}}],expenses:[{id:'e1',category:'Rent',description:'September rent',date:'2026-09-28T00:00:00Z',amount:50000}],attendance:[],profile:{photo:''},version:1,receipts:[{id:'r1',paymentId:'p1',number:'REC-00001',remainingAmount:150000}]};
const context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:1,recordVideo:{dir:'/downloads',size:{width:1280,height:800}},acceptDownloads:true});const page=await context.newPage();
await page.route('**/api/**',async route=>{const url=new URL(route.request().url()),res=url.pathname.split('/').at(-1),method=route.request().method();if(res==='me')return route.fulfill({json:{email:'anita@example.test',name:'Anita Rao',picture:''}});if(method==='GET'){if(res==='profile')return route.fulfill({json:data.profile});if(res==='summary')return route.fulfill({json:{students:1,batches:1,collection:30000,pending:150000,overdue:150000,expenses:50000,profit:-20000,recentPayments:data.payments,pendingFees:data.fees}});if(res==='export')return route.fulfill({json:data});if(res==='r1')return route.fulfill({json:{id:'r1',number:'REC-00001',instituteName:'ABC Coaching',payment:{...data.payments[0],student:data.students[0],fee:data.fees[0]},remainingAmount:150000}});return route.fulfill({json:res==='export'?data:(data[res]||[])})}const body=route.request().postDataJSON();if(res==='profile')data.profile=body;else if(res==='attendance'){const old=data.attendance.find(a=>a.studentId===body.studentId&&a.date===body.date+'T00:00:00.000Z');if(old)old.status=body.status;else data.attendance.push({...body,id:'a1',date:body.date+'T00:00:00.000Z'})}else if(res==='import'){data=body;return route.fulfill({json:{students:data.students.length,batches:data.batches.length,fees:data.fees.length,payments:data.payments.length},status:201})}else if(res==='expenses')data.expenses.push({...body,id:'e2',amount:Math.round(Number(body.amount)*100),date:body.date+'T00:00:00.000Z'});return route.fulfill({json:{...body,id:'new'},status:201})});
async function wait(ms=3200){await page.waitForTimeout(ms)}
async function caption(title,subtitle){await page.evaluate(({title,subtitle})=>{document.getElementById('demo-caption')?.remove();const d=document.createElement('div');d.id='demo-caption';Object.assign(d.style,{position:'fixed',bottom:'18px',left:'50%',transform:'translateX(-50%)',zIndex:'99999',padding:'14px 23px',borderRadius:'12px',background:'rgba(15,42,36,.94)',color:'#fff',font:'17px/1.4 Arial,sans-serif',boxShadow:'0 5px 25px #0004',maxWidth:'85%',textAlign:'center'});d.innerHTML='<strong>'+title+'</strong><br><span style="font-size:13px">'+subtitle+'</span>';document.body.appendChild(d)},{title,subtitle});await wait(2500)}
async function nav(label){await page.locator('aside nav button').filter({hasText:label}).nth(label==='Fees'?0:label==='Pending Fees'?0:0).click();await wait(500);console.log('NAV',label,await page.locator('.page-head h1').innerText())}
try{for(let i=0;i<50;i++){try{if((await fetch(root+'/home')).ok)break}catch{}await new Promise(r=>setTimeout(r,250))}
await page.goto(root+'/home');await caption('Fee Manager | Full demo','Sample records only. No real student data or messages are used.');
await page.goto(root+'/privacy');await caption('Home & Privacy','Read what the app stores in your own Google Sheet and how to remove access.');
await page.goto(root);await page.getByRole('heading',{name:'Dashboard'}).waitFor();await caption('Google account dashboard','Each teacher signs in with Google. Their records belong to their own Drive Sheet.');
await page.getByRole('button',{name:'Change profile photo'}).click();await caption('Your profile','The avatar uses your first initial, Google photo, or a custom upload.');await page.locator('.dialog-head .close').click();
await nav('Batches');await caption('Batches','Add a course, teacher, time and monthly fee.');await page.getByRole('button',{name:'+ Add batch'}).click();await caption('Batch form','Use Add batch to create or edit a class group.');await page.locator('.dialog-head .close').click();
await nav('Students');await caption('Students','Parent mobile, joining date, optional photo and notes stay with each student.');await page.getByRole('button',{name:'+ Add student'}).click();await caption('Student form','Choose a batch and save the student; edit later without losing payment history.');await page.locator('.dialog-head .close').click();
await nav('Fees');await caption('Monthly fees','A discount reduces the balance. Overdue fees are marked red after the due date.');console.log('BUTTONS',await page.locator('.page-head button').allInnerTexts());await page.getByRole('button',{name:/Create monthly fee|Create fee/}).click();await caption('Fee form','Choose a student and month; add a concession before saving.');await page.locator('.dialog-head .close').click();
await nav('Pending Fees');await caption('Pending fees','See the balance, due date, parent contact and reminder action.');await page.getByRole('button',{name:'Reminder',exact:true}).click();await caption('WhatsApp reminder','Review the drafted text and recipient. You press Send yourself.');await page.locator('.dialog-head .close').click();
await nav('Payments');await caption('Installments & receipts','Record each partial payment. Receipts can be downloaded or shared.');await page.getByRole('button',{name: /REC-00001/}).click();await caption('Payment receipt','Print, download PDF, or use the phone share menu where supported.');await page.locator('.dialog-head .close').click();
await nav('Expenses');await caption('Expenses','Track rent, teacher salary and supplies.');await page.getByRole('button',{name:'+ Add expense'}).click();await caption('Expense form','Add category, description, amount and date.');await page.locator('.dialog-head .close').click();
await nav('Reports');await caption('Monthly report','Compare received payments, expenses, net and pending fees. Export CSV or PDF.');
await nav('Attendance');await page.getByLabel('Attendance batch').selectOption('b1');await caption('Batch attendance','Choose a date and batch, then mark Present or Absent.');
await nav('Backup');await caption('Backup export','Download all records as a private JSON file.');await page.getByLabel('Choose backup JSON').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await caption('Backup restore','Review the counts. Restoring replaces this account current records; back up first.');
await page.getByRole('button',{name:'Change language'}).click();await caption('Hindi & English','Toggle the interface language. Some supporting copy remains in English.');await page.locator('.topbar .theme').filter({hasText:'डार्क मोड'}).click();await caption('Dark mode','The interface keeps your light or dark choice on this device.');
await page.goto(root+'/guide');await caption('Guide / Help','Written steps are available here in English and Hinglish. This video lives here too.');
}catch(e){console.error('Demo recording error',e);process.exitCode=1}finally{await context.close();console.log('VIDEO',await page.video()?.path());await browser.close();server.kill('SIGTERM')}
