import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import vm from 'node:vm';import ts from 'typescript';
const src=readFileSync(new URL('../lib/store.ts',import.meta.url),'utf8');const a=src.indexOf('function checkedPhoto('),b=src.indexOf('export function validateBackup('),c=src.indexOf('function change(',b);const snippet=src.slice(a,src.indexOf('function required(',a))+src.slice(b,c).replace('export function','function');const js=ts.transpileModule(snippet,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const sandbox={dateOnly:(v)=>{const d=new Date(v+'T00:00:00.000Z');if(isNaN(d.getTime())||d.toISOString().slice(0,10)!==v)throw Error('Invalid date');return d},monthValid:(v)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(v)};vm.runInNewContext(js+';globalThis.validateBackup=validateBackup',sandbox);const validateBackup=sandbox.validateBackup;
const raw=JSON.parse(readFileSync('/tmp/live-fee-export-response.json','utf8')).content;const base=JSON.parse(raw);
if(base.batches.length!==1||base.students.length!==1)throw Error('Baseline no longer matches original snapshot - do not use');
const source=JSON.parse(readFileSync('/tmp/live-fee-export-current.json','utf8'));
if(!source.batches.some(x=>x.name==='TEST Batch 01 - Maths')||source.students.length!==1)throw Error('Current snapshot changed - stop');
const state=structuredClone(source);const now=new Date().toISOString(),today='2026-09-29T00:00:00.000Z';
for(let n=2;n<=10;n++){state.batches.push({id:randomUUID(),name:`TEST Batch ${String(n).padStart(2,'0')} - ${['Science','English','Hindi','Physics','Chemistry','Biology','History','Geography','Computer'][n-2]}`,courseName:'TEST '+['Science','English','Hindi','Physics','Chemistry','Biology','History','Geography','Computer'][n-2],teacherName:'TEST Teacher '+String.fromCharCode(64+n),timing:`TEST ${8+n}:00 - ${9+n}:00`,monthlyFee:(800+n*100)*100,status:'Active',createdAt:now})}
const testB=state.batches.filter(x=>x.name.startsWith('TEST Batch')).sort((a,b)=>a.name.localeCompare(b.name));if(testB.length!==10)throw Error('Expected 10 test batches');
const seats=Array.from({length:10},()=>new Set());const students=[];
for(let i=1;i<=150;i++){let first=(i-1)%10,second=(i+4)%10;const batchIds=first===second?[testB[first].id]:[testB[first].id,testB[second].id];const st={id:randomUUID(),studentId:`TEST-${String(i).padStart(4,'0')}`,name:`TEST Student ${String(i).padStart(3,'0')}`,parentName:`TEST Parent ${String(i).padStart(3,'0')}`,mobile:'0000000000',batchId:batchIds[0],batchIds,monthlyFee:(700+i%9*100)*100,joiningDate:today,notes:'TEST synthetic record; no real contact',photo:'',status:'Active',createdAt:now};students.push(st);state.students.push(st);for(const bid of batchIds)seats[testB.findIndex(b=>b.id===bid)].add(st.id)}
// Exactly 30 seats per batch: deterministic second assignment shifts by five groups.
if(seats.some(x=>x.size!==30))throw Error('Unexpected seat layout '+seats.map(x=>x.size));
const counts=seats.map(x=>x.size);if(counts.some(n=>n!==30))throw Error('Seat counts '+counts);
for(let i=0;i<30;i++){const st=students[i],batchId=st.batchIds[0],fee={id:randomUUID(),studentId:st.id,batchId,month:'2026-09',baseFee:st.monthlyFee,discount:i%5===0?10000:0,totalFee:st.monthlyFee-(i%5===0?10000:0),dueDate:today};state.fees.push(fee);if(i%3!==2){let amount=i%3===0?Math.floor(fee.totalFee/2):fee.totalFee,p={id:randomUUID(),studentId:st.id,feeId:fee.id,amount,paymentDate:today,mode:i%2?'UPI':'Cash',notes:'TEST synthetic payment; no money collected',createdAt:now};state.payments.push(p);state.receipts.push({id:randomUUID(),paymentId:p.id,number:`TEST-REC-${String(i+1).padStart(5,'0')}`,remainingAmount:fee.totalFee-amount,createdAt:now})}}
for(let i=0;i<30;i++){const st=students[i];state.attendance.push({id:randomUUID(),studentId:st.id,batchId:st.batchIds[0],date:today,status:i%5?'Present':'Absent'})}
state.expenses.push({id:randomUUID(),category:'Other',description:'TEST synthetic expense, not real spending',amount:50000,date:today,createdAt:now});
validateBackup(state);const summary={students:state.students.length,batches:state.batches.length,payments:state.payments.length};
writeFileSync('/downloads/fee-manager-TEST-150-students.json',JSON.stringify(state,null,2));
console.log(JSON.stringify({batches:state.batches.length,students:state.students.length,testSeats:counts,fees:state.fees.length,payments:state.payments.length,receipts:state.receipts.length,expenses:state.expenses.length,attendance:state.attendance.length,summary,bytes:Buffer.byteLength(JSON.stringify(state))},null,2));
