import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
const root='http://127.0.0.1:3210';const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});
let server=spawn('./node_modules/.bin/next',['start','-p','3210'],{stdio:['ignore','pipe','pipe'],env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'}});let logs='';server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);
async function waitServer(){for(let i=0;i<100;i++){try{let r=await fetch(root);if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,200))}throw Error('Server did not start: '+logs)}
await fs.mkdir('artifacts/frames',{recursive:true});
await fs.mkdir('artifacts/videos',{recursive:true});const context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:1,acceptDownloads:true,recordVideo:{dir:'artifacts/videos',size:{width:1280,height:800}}});const page=await context.newPage();const failures=[];page.on('pageerror',e=>failures.push(e.message));let frame=0;
async function shot(label,hold=6){await page.screenshot({path:`artifacts/${label}.png`,fullPage:true});let buf=await page.screenshot();for(let i=0;i<hold;i++)await fs.writeFile(`artifacts/frames/${String(++frame).padStart(4,'0')}.png`,buf)}
async function clickText(text){let match=page.getByRole('button',{name:text,exact:true});if(await match.count())await match.last().click();else await page.locator('aside nav button').filter({hasText:text}).first().click()}
async function api(path,opts={}){let r=await page.evaluate(async ({path,opts})=>{let x=await fetch('/api/'+path,{...opts,headers:{'Content-Type':'application/json'}});return {status:x.status,data:await x.json()}},{path,opts});if(r.status>=400)throw Error(path+': '+JSON.stringify(r));return r.data}
function body(value){return {method:'POST',body:JSON.stringify(value)}}
try{await waitServer();await page.goto(root);await page.getByRole('heading',{name:'Fee Manager'}).waitFor();await shot('01-login',5);await page.getByLabel('Email').fill(process.env.ADMIN_EMAIL||'demo@example.test');await page.getByLabel('Password').fill(process.env.ADMIN_PASSWORD||'TemporaryDemoPassword!2026');await clickText('Sign in');await page.getByRole('heading',{name:'Dashboard'}).waitFor();await shot('02-dashboard-empty',5);
await clickText('Batches');await clickText('+ Add batch');await page.getByLabel('Batch name').fill('Foundation A');await page.getByLabel('Course name').fill('Mathematics');await page.getByLabel('Teacher name').fill('Anita Rao');await page.getByLabel('Timing').fill('4:00–5:00 PM');await page.getByLabel('Monthly fee (₹)').fill('2000');await clickText('Save');await page.getByText('Foundation A').first().waitFor();await shot('03-batches',5);let batch=(await api('batches'))[0];assert.equal(batch.name,'Foundation A');
await clickText('Students');await clickText('+ Add student');await page.getByLabel('Student ID').fill('STU-001');await page.getByLabel('Student name').fill('Rahul Sharma');await page.getByLabel('Parent name').fill('Sunita Sharma');await page.getByLabel('Mobile number').fill('9876543210');await page.locator('.dialog select').first().selectOption(batch.id);await page.getByLabel('Monthly fee (₹)').fill('2000');await clickText('Save');await page.getByText('Rahul Sharma').first().waitFor();await shot('04-students',5);let student=(await api('students'))[0];assert.equal(student.batchId,batch.id);
await clickText('Fees');await clickText('+ Create fee');await page.locator('.dialog select').first().selectOption(student.id);await page.getByLabel('Fee month').fill('2026-09');await page.getByLabel('Total fee (₹)').fill('2000');await page.getByLabel('Due date').fill('2026-10-15');await clickText('Save');await page.getByText('Pending',{exact:true}).waitFor();await shot('05-pending-fee',5);let fee=(await api('fees'))[0];assert.equal(fee.status,'Pending');assert.equal(fee.pendingAmount,200000);
await clickText('Pending Fees');await shot('06-pending-page',5);await page.getByRole('button',{name:'Reminder',exact:true}).click();assert.match(await page.locator('textarea').inputValue(),/₹2,000\.00/);await shot('07-reminder',4);await clickText('Cancel');
await clickText('Payments');await clickText('+ Record payment');await page.locator('.dialog select').first().selectOption(student.id);await page.locator('.dialog select').nth(1).selectOption(fee.id);await page.getByLabel('Amount (₹)').fill('1000');await page.getByLabel('Payment date').fill('2026-09-28');await page.locator('.dialog select').nth(2).selectOption('UPI');await clickText('Record payment');await page.getByText('REC-00001').first().waitFor();await shot('08-receipt-partial',5);await clickText('×');fee=(await api('fees'))[0];assert.equal(fee.status,'Partial');assert.equal(fee.pendingAmount,100000);assert.equal((await api('summary')).collection,100000);await clickText('Fees');await shot('09-partial',5);
await page.getByRole('button',{name:'Pay',exact:true}).click();await page.getByLabel('Amount (₹)').fill('1000');await page.getByLabel('Payment date').fill('2026-09-28');await clickText('Record payment');await page.getByText('REC-00002').first().waitFor();await shot('10-receipt-paid',6);let [p1,p2]=await api('payments');assert.equal(p1.receipt.number,'REC-00002');assert.equal(p2.receipt.number,'REC-00001');assert.equal(p1.receipt.remainingAmount,0);const downloadPromise=page.waitForEvent('download');await clickText('Download PDF');const download=await downloadPromise;await download.saveAs('artifacts/receipt-test.pdf');await clickText('×');fee=(await api('fees'))[0];assert.equal(fee.status,'Paid');assert.equal(fee.pendingAmount,0);assert.equal(fee.payments.length,2);await clickText('Dashboard');await shot('11-dashboard-paid',7);let summary=await api('summary');assert.equal(summary.collection,200000);assert.equal(summary.pending,0);
await clickText('Students');await page.getByLabel('Search student').fill('STU-001');assert.equal(await page.locator('tbody tr').count(),1);await page.getByLabel('Filter by batch').selectOption(batch.id);assert.equal(await page.locator('tbody tr').count(),1);await shot('12-search-filter',5);await page.getByLabel('Search student').fill('not found');assert.equal(await page.locator('tbody tr').count(),0);await page.getByLabel('Search student').fill('');await page.locator('tbody tr').first().getByRole('button',{name:'View'}).click();await page.getByText('Payment history').last().waitFor();await shot('13-student-profile',5);await clickText('×');
page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Deactivate',exact:true}).click();
await page.getByText('Inactive',{exact:true}).waitFor();assert.equal((await api('payments')).length,2);await clickText('Dashboard');await clickText('☾ Dark mode');await shot('14-dark-dashboard',7);
await page.setViewportSize({width:390,height:844});await shot('15-mobile-dashboard',7);await page.getByRole('button',{name:'☰'}).click();await shot('16-mobile-navigation',5);await page.locator('aside nav button').filter({hasText:'Pending Fees'}).click();await shot('17-mobile-pending',6);assert.equal(failures.length,0,failures.join('; '));console.log('PASS all 15 requested checkpoints. '+frame+' captured screen frames.');
}catch(e){console.error('FAIL',e,logs,failures);process.exitCode=1}finally{await context.close();console.log('VIDEO',await page.video()?.path());await browser.close();server.kill('SIGTERM')}
