import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';import ts from 'typescript';
const source=await fs.readFile(new URL('../lib/store.ts',import.meta.url),'utf8');const start=source.indexOf('export function validateBackup('),end=source.indexOf('function change(',start);const helper=source.slice(source.indexOf('function checkedPhoto('),source.indexOf('function required(',source.indexOf('function checkedPhoto(')));const code=ts.transpileModule(helper+source.slice(start,end).replace('export function','function'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const sandbox={dateOnly:(s)=>{const d=new Date(s+'T00:00:00.000Z');if(isNaN(d.getTime())||d.toISOString().slice(0,10)!==s)throw Error('Invalid date');return d},monthValid:(s)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(s)};vm.runInNewContext(code+';globalThis.validateBackup=validateBackup',sandbox);const {validateBackup}=sandbox;
const date='2026-09-28T00:00:00.000Z';const sample=()=>({version:1,batches:[{id:'b',name:'Batch',courseName:'Math',teacherName:'Teacher',timing:'5 PM',monthlyFee:200000,status:'Active'}],students:[{id:'s',studentId:'S-1',name:'Ravi',parentName:'Neha',mobile:'9876543210',batchId:'b',monthlyFee:200000,joiningDate:date,status:'Active'}],fees:[{id:'f',studentId:'s',month:'2026-09',totalFee:180000,baseFee:200000,discount:20000,dueDate:date}],payments:[{id:'p',studentId:'s',feeId:'f',amount:30000,paymentDate:date,mode:'UPI'}],receipts:[{id:'r',paymentId:'p',number:'REC-00001',remainingAmount:150000}],expenses:[{id:'e',category:'Rent',description:'Monthly',amount:50000,date}],attendance:[{id:'a',studentId:'s',batchId:'b',date,status:'Present'}]});
test('valid export-shaped backup is accepted',()=>{const data=sample();assert.equal(validateBackup(data).students[0].name,'Ravi')});
test('invalid references, payments and records are rejected before replace',()=>{for(const mutate of [x=>x.students[0].batchId='other',x=>x.payments[0].amount=200000,x=>x.fees[0].discount=30000,x=>x.attendance[0].studentId='other',x=>x.students[0].photo='javascript:alert(1)',x=>x.receipts[0].id='b']){const data=sample();mutate(data);assert.throws(()=>validateBackup(data))}});
test('backup records preserve old version with optional fields absent',()=>{const x=sample();delete x.expenses;delete x.attendance;delete x.students[0].photo;assert.equal(validateBackup(x).expenses.length,0)});
test('one student can enroll in two batches and retain old export shape',()=>{const x=sample();x.batches.push({...x.batches[0],id:'b2',name:'Science'});x.students[0].batchIds=['b','b2'];x.fees.push({...x.fees[0],id:'f2',batchId:'b2'});x.fees[0].batchId='b';x.attendance.push({...x.attendance[0],id:'a2',batchId:'b2'});assert.equal(validateBackup(x).students[0].batchIds.length,2);const old=sample();assert.equal(validateBackup(old).students[0].batchId,'b')});
test('multi-batch backup rejects foreign batch, duplicate fee and duplicate attendance',()=>{const x=sample();x.batches.push({...x.batches[0],id:'b2',name:'Science'});x.students[0].batchIds=['b','b2'];x.fees[0].batchId='b';assert.throws(()=>{const bad=structuredClone(x);bad.students[0].batchIds=['b','other'];validateBackup(bad)});assert.throws(()=>{const bad=structuredClone(x);bad.fees.push({...bad.fees[0],id:'f2'});validateBackup(bad)});assert.throws(()=>{const bad=structuredClone(x);bad.attendance.push({...bad.attendance[0],id:'a2'});validateBackup(bad)})});

test("coaching name survives backup restore and invalid names are rejected",()=>{const x=sample();x.profile={photo:"",instituteName:"TEST Coaching"};assert.equal(validateBackup(x).profile.instituteName,"TEST Coaching");x.profile.instituteName="bad\nname";assert.throws(()=>validateBackup(x))});
