import {chromium} from 'playwright-core';import {spawn} from 'node:child_process';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const state=JSON.parse(readFileSync('/downloads/fee-manager-TEST-150-students.json','utf8'));
const bm=new Map(state.batches.map(b=>[b.id,b])),sm=new Map(state.students.map(s=>[s.id,s])),fm=new Map(state.fees.map(f=>[f.id,f]));
const payments=state.payments.map(p=>({...p,student:sm.get(p.studentId),fee:{...fm.get(p.feeId),batch:bm.get(fm.get(p.feeId).batchId)},receipt:state.receipts.find(r=>r.paymentId===p.id)}));
const fees=state.fees.map(f=>{const st=sm.get(f.studentId),paid=payments.filter(p=>p.feeId===f.id).reduce((a,p)=>a+p.amount,0),batch=bm.get(f.batchId||st.batchId);return {...f,student:{...st,batch},batch,paidAmount:paid,pendingAmount:f.totalFee-paid,status:paid>=f.totalFee?'Paid':paid>0?'Partial':'Pending'}});
const students=state.students.map(s=>({...s,batch:bm.get(s.batchId),batches:(s.batchIds||[s.batchId]).map(id=>bm.get(id)),fees:fees.filter(f=>f.studentId===s.id),pendingAmount:fees.filter(f=>f.studentId===s.id).reduce((sum,f)=>sum+f.pendingAmount,0)}));
const batches=state.batches.map(b=>({...b,_count:{students:students.filter(s=>(s.batchIds||[s.batchId]).includes(b.id)).length}}));
const summary={students:students.length,batches:batches.length,collection:payments.reduce((sum,p)=>sum+p.amount,0),pending:fees.reduce((sum,f)=>sum+f.pendingAmount,0),overdue:0,expenses:50000,profit:0,recentPayments:payments.slice(0,8),pendingFees:fees.filter(f=>f.pendingAmount>0).slice(0,8)};
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const server=spawn('./node_modules/.bin/next',['start','-p','3213'],{env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:'ignore'});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const data={students,batches,fees,payments,summary,expenses:state.expenses,attendance:state.attendance,profile:{photo:''}};
await page.route('**/api/**',route=>{const name=new URL(route.request().url()).pathname.split('/').pop();if(name==='me')return route.fulfill({json:{email:'test@example.invalid',name:'TEST Admin'}});if(name==='plan')return route.fulfill({json:{status:'active',due:'2026-11-02',grace:'2026-11-09',owner:false,backupError:null}});return route.fulfill({json:data[name]||[]})});
try{for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:3213/home')).ok)break}catch{}await new Promise(r=>setTimeout(r,250))}const start=performance.now();await page.goto('http://127.0.0.1:3213/');await page.getByRole('heading',{name:'Dashboard'}).waitFor();await page.getByText('151',{exact:true}).first().waitFor();const dashboardMs=Math.round(performance.now()-start);await page.locator('aside nav button').filter({hasText:'Students'}).click();await page.getByText('151 students').waitFor();assert.equal(await page.locator('main table tbody tr').count(),151);await page.screenshot({path:'/downloads/extreme-150-students-desktop.png',fullPage:false});await page.getByPlaceholder('Search name, ID, mobile').fill('TEST-0075').catch(async()=>{await page.getByRole('textbox',{name:'Search student'}).fill('TEST-0075')});await page.getByText('1 students').waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/downloads/extreme-150-search-mobile.png'});assert.deepEqual(errors,[]);console.log(JSON.stringify({dashboardMs,students:students.length,batches:batches.length,fees:fees.length,payments:payments.length,errors}));}catch(e){console.error('FAIL',e,errors);process.exitCode=1}finally{await browser.close();server.kill('SIGTERM')}
