import {test} from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {readFileSync} from 'node:fs';import ts from 'typescript';import vm from 'node:vm';
const code=ts.transpileModule(readFileSync('lib/store-contract.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const module={exports:{}};vm.runInNewContext(code,{exports:module.exports,require:x=>{if(x==='node:crypto')return {createHmac,...process.getBuiltinModule('crypto')};throw Error(x)},Buffer,Date,TextDecoder});const {validSignature,parseStoreEvent,intervalActive,payloadHash}=module.exports;
const secret='test-only-'.repeat(5),now=1780291200000,stamp=String(now/1000),event={eventId:'evt-1',orderId:'ord-1',googleIssuer:'https://accounts.google.com',googleSub:'123456789',product:'FEE_MANAGER',plan:'MONTHLY',startsAt:'2026-06-01T00:00:00.000Z',expiresAt:'2026-07-01T00:00:00.000Z',action:'GRANT'},raw=Buffer.from(JSON.stringify(event));const sig=createHmac('sha256',secret).update(stamp+'.').update(raw).digest('hex');
test('HMAC binds exact raw bytes, timestamp and secret',()=>{assert.equal(validSignature(raw,stamp,sig,secret,now),true);assert.equal(validSignature(Buffer.from(raw+' '),stamp,sig,secret,now),false);assert.equal(validSignature(raw,stamp,sig,secret+'x',now),false);assert.equal(validSignature(raw,stamp,'bad',secret,now),false);assert.equal(validSignature(raw,stamp,sig,secret,now+300001),false);assert.equal(validSignature(raw,stamp,sig,secret,now-300001),false);assert.equal(validSignature(raw,stamp,sig,secret,now+300000),true)});
test('Strict identity/product/action/30-day contract',()=>{assert.equal(parseStoreEvent(raw.toString()).orderId,'ord-1');for(const patch of [{googleIssuer:'evil'},{googleSub:'email@example.com'},{plan:'YEARLY'},{product:'OTHER'},{action:'RENEW'},{expiresAt:'2026-07-02T00:00:00.000Z'},{extra:true}])assert.throws(()=>parseStoreEvent(JSON.stringify({...event,...patch})));assert.notEqual(payloadHash(raw),payloadHash(Buffer.from(raw+' ')))});
test('Access starts inclusively and ends exclusively with no grace',()=>{assert.equal(intervalActive(event.startsAt,event.expiresAt,Date.parse(event.startsAt)-1),false);assert.equal(intervalActive(event.startsAt,event.expiresAt,Date.parse(event.startsAt)),true);assert.equal(intervalActive(event.startsAt,event.expiresAt,Date.parse(event.expiresAt)-1),true);assert.equal(intervalActive(event.startsAt,event.expiresAt,Date.parse(event.expiresAt)),false)});

test('new signup manual paid-date fallback must not accept expired dates',()=>{const source=readFileSync('lib/entitlements.ts','utf8');assert.match(source,/sqlDate\(tenant.paid_through\)!>=dayInIndia/)});
