'use client';
import {useEffect,useState} from 'react';
import {jsPDF} from 'jspdf';
type Rec=Record<string,any>;
const money=(n:number)=>'₹'+((n||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(d:string)=>d?.slice(0,10)||'';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const month=()=>today().slice(0,7);
const nav=['Dashboard','Students','Batches','Fees','Payments','Pending Fees'];
async function api(path:string,init?:RequestInit){const r=await fetch('/api/'+path,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function Badge({status}:{status:string}){return <span className={'badge '+status?.toLowerCase()}>{status}</span>}
export default function Home(){
const [auth,setAuth]=useState<boolean|null>(null),[email,setEmail]=useState(''),[theme,setTheme]=useState('light');
const [page,setPage]=useState('Dashboard'),[batches,setBatches]=useState<Rec[]>([]),[students,setStudents]=useState<Rec[]>([]),[fees,setFees]=useState<Rec[]>([]),[payments,setPayments]=useState<Rec[]>([]),[summary,setSummary]=useState<Rec>({});
const [modal,setModal]=useState(''),[draft,setDraft]=useState<Rec>({}),[search,setSearch]=useState(''),[batchFilter,setBatchFilter]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<Rec|null>(null),[reminder,setReminder]=useState(''),[showMobile,setShowMobile]=useState(false);
useEffect(()=>{let t=localStorage.getItem('fee-theme')||'light';setTheme(t);document.documentElement.dataset.theme=t;api('auth/me').then(v=>{setEmail(v.email);setAuth(true)}).catch(()=>setAuth(false));if(new URLSearchParams(location.search).has('auth_error'))setError('Google sign-in failed. Please retry or contact the app owner.')},[]);
async function refresh(){try{const [b,s,f,p,x]=await Promise.all(['batches','students','fees','payments','summary'].map(k=>api(k)));setBatches(b);setStudents(s);setFees(f);setPayments(p);setSummary(x)}catch(e:any){setError(e.message)}}
useEffect(()=>{if(auth)refresh()},[auth]);
function toggleTheme(){let t=theme==='light'?'dark':'light';setTheme(t);localStorage.setItem('fee-theme',t);document.documentElement.dataset.theme=t}

async function logout(){await api('auth/logout',{method:'POST'});setAuth(false);setPage('Dashboard');setEmail('')}
function open(kind:string,row:Rec={}){setError('');setNotice('');setDraft(row.id?{...row,joiningDate:date(row.joiningDate),dueDate:date(row.dueDate),monthlyFee:row.monthlyFee/100,totalFee:row.totalFee/100}:{joiningDate:today(),dueDate:today(),paymentDate:today(),month:month(),mode:'Cash',...row});setModal(kind)}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let endpoint=modal==='student'?'students':modal==='batch'?'batches':modal==='fee'?'fees':'payments';let result=await api(endpoint,{method:draft.id?'PATCH':'POST',body:JSON.stringify(draft)});setModal('');await refresh();setNotice(modal==='payment'?'Payment recorded. Receipt '+result.receipt.number+' is ready.':'Saved successfully.');if(modal==='payment')await showReceipt(result.receipt.id)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
async function setStatus(kind:string,row:Rec){const next=row.status==='Active'?'Inactive':'Active';if(!window.confirm(`${next==='Inactive'?'Deactivate':'Activate'} ${kind==='students'?row.name:row.name}? Payment history will be kept.`))return;try{await api(kind,{method:'PATCH',body:JSON.stringify({id:row.id,status:next})});await refresh();setNotice(`${kind==='students'?'Student':'Batch'} marked ${next.toLowerCase()}.`)}catch(e:any){setError(e.message)}}
async function showReceipt(id:number){try{let r=await api('receipt/'+id);setReceipt(r);setModal('receipt')}catch(e:any){setError(e.message)}}
function sendReminder(f:Rec){let s=f.student;setReminder(`Dear Parent,\n\nThe monthly fee of ${money(f.pendingAmount)} for ${s.name} (${f.month}) is pending.\n\nPlease complete the payment at your earliest convenience.\n\nThank you,\nABC Coaching`);setModal('reminder')}
async function copyReminder(){try{await navigator.clipboard.writeText(reminder);setNotice('Reminder copied. Nothing was sent.');setModal('')}catch{setError('Copy failed. Select the text and copy it manually.')}}
async function receiptPdf(){if(!receipt)return;const p=receipt.payment;try{const fontBytes=await (await fetch('/fonts/DejaVuSans.ttf')).arrayBuffer();const binary=Array.from(new Uint8Array(fontBytes),b=>String.fromCharCode(b)).join('');const doc=new jsPDF();doc.addFileToVFS('DejaVuSans.ttf',btoa(binary));doc.addFont('DejaVuSans.ttf','DejaVu','normal');doc.setFont('DejaVu');doc.setFontSize(18);doc.text(receipt.instituteName,20,25);doc.setFontSize(11);const lines=[`Receipt: ${receipt.number}`,`Student: ${p.student.name}`,`Student ID: ${p.student.studentId}`,`Fee month: ${p.fee.month}`,`Amount paid: ${money(p.amount)}`,`Payment date: ${date(p.paymentDate)}`,`Payment mode: ${p.mode}`,`Remaining amount: ${money(receipt.remainingAmount)}`];lines.forEach((line,i)=>doc.text(line,20,44+i*10));doc.save(receipt.number+'.pdf')}catch{setError('Could not generate PDF. Try Print receipt instead.')}}
const filteredStudents=students.filter(s=>(!batchFilter||s.batchId===batchFilter)&&(!search||[s.name,s.studentId,s.mobile].some((v:string)=>v?.toLowerCase().includes(search.toLowerCase()))));
const filteredFees=fees.filter(f=>(!batchFilter||f.student.batchId===batchFilter)&&(!search||[f.student.name,f.student.studentId,f.student.mobile].some((v:string)=>v?.toLowerCase().includes(search.toLowerCase()))));
const pending=filteredFees.filter(f=>f.pendingAmount>0);
if(auth===null)return <div className="loading">Loading Fee Manager…</div>;
if(!auth)return <main className="login-page"><div className="login-card"><button className="theme small float" onClick={toggleTheme}>{theme==='light'?'☾ Dark':'☀ Light'}</button><div className="brand-icon">₹</div><p className="eyebrow">COACHING INSTITUTE</p><h1>Fee Manager</h1><p className="muted">Sign in with your Google account. Your records are saved in a spreadsheet in your own Google Drive. Only your signed-in account can access them through this app.</p><a className="primary full google-login" href="/api/auth/start">Sign in with Google</a><p className="muted">For testing only. Do not add real student data until Google login, backup and security review are complete.</p>{error&&<p role="alert" className="error">{error}</p>}</div></main>;
return <div className="app"><aside className={'sidebar '+(showMobile?'expanded':'')}><div className="logo"><div className="brand-icon">₹</div><div><strong>Fee Manager</strong><small>Your Google Drive</small></div></div><p className="side-label">WORKSPACE</p><nav>{nav.map(n=><button key={n} className={page===n?'selected':''} onClick={()=>{setPage(n);setSearch('');setBatchFilter('');setShowMobile(false)}}><span className="nav-icon">{({'Dashboard':'◫','Students':'♙','Batches':'▣','Fees':'₹','Payments':'↗','Pending Fees':'◷'} as Rec)[n]}</span>{n}</button>)}</nav><div className="sidebar-bottom">Simple fee management<br/>for your institute</div></aside><main className="main"><header className="topbar"><button className="menu" onClick={()=>setShowMobile(!showMobile)}>☰</button><span className="breadcrumb">Workspace <b>/</b> {page}</span><div className="top-actions"><button className="theme" onClick={toggleTheme}>{theme==='light'?'☾ Dark mode':'☀ Light mode'}</button><span className="avatar" title={email}>A</span><span className="admin-label">{email}</span><button className="text-button" onClick={logout}>Logout</button></div></header><div className="content"><div className="page-head"><div><p className="eyebrow">OVERVIEW / {page.toUpperCase()}</p><h1>{page}</h1><p className="muted">{({'Dashboard':'Keep every fee on track, in one place.','Students':'Manage student records and fee histories.','Batches':'Organize students by course and timing.','Fees':'Track monthly dues and payment status.','Payments':'Every payment recorded, every receipt ready.','Pending Fees':'Follow up on balances without losing track.'} as Rec)[page]}</p></div><div>{page==='Students'&&<button className="primary" onClick={()=>open('student')}>+ Add student</button>}{page==='Batches'&&<button className="primary" onClick={()=>open('batch')}>+ Add batch</button>}{page==='Fees'&&<button className="primary" onClick={()=>open('fee')}>+ Create fee</button>}{page==='Payments'&&<button className="primary" onClick={()=>open('payment')}>+ Record payment</button>}</div></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{error&&!modal&&<div className="error">{error}</div>}
{page==='Dashboard'&&<><div className="metrics">{[['Total students',summary.students,'◉'],['Total batches',summary.batches,'▣'],['This month collection',money(summary.collection),'↗'],['Total pending fees',money(summary.pending),'◷'],['Total overdue fees',money(summary.overdue),'!']].map(([label,value,icon],i)=><div className={'metric m'+i} key={String(label)}><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><small>{i===2?'Received this month':i>2?'Across all fee records':'Currently in system'}</small></div>)}</div><div className="two-cols"><section className="panel"><div className="panel-title"><div><h2>Recent payments</h2><p>Latest transactions</p></div><button className="link" onClick={()=>setPage('Payments')}>View all →</button></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Amount</th><th>Payment date</th><th>Mode</th></tr></thead><tbody>{(summary.recentPayments||[]).map((p:Rec)=><tr key={p.id}><td><b>{p.student.name}</b></td><td className="emphasis">{money(p.amount)}</td><td>{date(p.paymentDate)}</td><td>{p.mode}</td></tr>)}</tbody></table>{!summary.recentPayments?.length&&<Empty message="No payments yet"/>}</div></section><section className="panel"><div className="panel-title"><div><h2>Pending fees</h2><p>Balances that need attention</p></div><button className="link" onClick={()=>setPage('Pending Fees')}>View all →</button></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Batch</th><th>Pending</th><th>Due date</th><th>Action</th></tr></thead><tbody>{(summary.pendingFees||[]).map((f:Rec)=><tr key={f.id}><td><b>{f.student.name}</b></td><td>{f.student.batch.name}</td><td className="pending-text">{money(f.pendingAmount)}</td><td>{date(f.dueDate)}</td><td><button className="link" onClick={()=>sendReminder(f)}>Send reminder</button></td></tr>)}</tbody></table>{!summary.pendingFees?.length&&<Empty message="No pending fees"/>}</div></section></div></>}
{page==='Students'&&<section className="panel"><div className="panel-title"><div><h2>All students</h2><p>{filteredStudents.length} students</p></div><Filter search={search} setSearch={setSearch} batch={batchFilter} setBatch={setBatchFilter} batches={batches}/></div><div className="table-wrap"><table><thead><tr><th>Student ID</th><th>Student</th><th>Parent / mobile</th><th>Batch</th><th>Monthly fee</th><th>Joined</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filteredStudents.map(s=><tr key={s.id}><td>{s.studentId}</td><td><b>{s.name}</b></td><td>{s.parentName}<small className="subtext">{s.mobile}</small></td><td>{s.batch.name}</td><td>{money(s.monthlyFee)}</td><td>{date(s.joiningDate)}</td><td><Badge status={s.status}/></td><td className="actions"><button onClick={()=>open('profile',s)}>View</button><button onClick={()=>open('student',s)}>Edit</button><button onClick={()=>setStatus('students',s)}>{s.status==='Active'?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table>{!filteredStudents.length&&<Empty message="No students found"/>}</div></section>}
{page==='Batches'&&<section className="panel"><div className="panel-title"><div><h2>All batches</h2><p>{batches.length} batches</p></div></div><div className="table-wrap"><table><thead><tr><th>Batch</th><th>Course</th><th>Teacher</th><th>Timing</th><th>Monthly fee</th><th>Students</th><th>Status</th><th>Actions</th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td><b>{b.name}</b></td><td>{b.courseName}</td><td>{b.teacherName}</td><td>{b.timing}</td><td>{money(b.monthlyFee)}</td><td>{b._count.students}</td><td><Badge status={b.status}/></td><td className="actions"><button onClick={()=>open('batchView',b)}>View</button><button onClick={()=>open('batch',b)}>Edit</button><button onClick={()=>setStatus('batches',b)}>{b.status==='Active'?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table>{!batches.length&&<Empty message="No batches yet"/>}</div></section>}
{['Fees','Pending Fees'].includes(page)&&<section className="panel"><div className="panel-title"><div><h2>{page==='Fees'?'Monthly fees':'Outstanding balances'}</h2><p>{page==='Fees'?filteredFees.length:pending.length} fee records</p></div><Filter search={search} setSearch={setSearch} batch={batchFilter} setBatch={setBatchFilter} batches={batches}/></div><div className="table-wrap"><table><thead><tr><th>Student</th>{page==='Pending Fees'&&<><th>Parent / mobile</th><th>Batch</th></>}<th>Fee month</th><th>Total fee</th><th>Paid</th><th>Pending</th><th>Due date</th><th>Status</th><th>Action</th></tr></thead><tbody>{(page==='Fees'?filteredFees:pending).map(f=><tr key={f.id}><td><b>{f.student.name}</b><small className="subtext">{f.student.studentId}</small></td>{page==='Pending Fees'&&<><td>{f.student.parentName}<small className="subtext">{f.student.mobile}</small></td><td>{f.student.batch.name}</td></>}<td>{f.month}</td><td>{money(f.totalFee)}</td><td className="emphasis">{money(f.paidAmount)}</td><td className="pending-text">{money(f.pendingAmount)}</td><td>{date(f.dueDate)}</td><td><Badge status={f.status}/></td><td className="actions">{f.pendingAmount>0&&<><button onClick={()=>open('payment',{feeId:f.id,studentId:f.studentId,amount:f.pendingAmount/100,month:f.month})}>Pay</button><button onClick={()=>sendReminder(f)}>Reminder</button></>}</td></tr>)}</tbody></table>{!(page==='Fees'?filteredFees:pending).length&&<Empty message="No matching fees"/>}</div></section>}
{page==='Payments'&&<section className="panel"><div className="panel-title"><div><h2>Payment history</h2><p>{payments.length} transactions</p></div></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Fee month</th><th>Amount</th><th>Payment date</th><th>Mode</th><th>Notes</th><th>Receipt</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td><b>{p.student.name}</b></td><td>{p.fee.month}</td><td className="emphasis">{money(p.amount)}</td><td>{date(p.paymentDate)}</td><td>{p.mode}</td><td>{p.notes||'—'}</td><td><button className="link" onClick={()=>showReceipt(p.receipt.id)}>{p.receipt.number} ↗</button></td></tr>)}</tbody></table>{!payments.length&&<Empty message="No payments yet"/>}</div></section>}
</div></main>
{modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget){setModal('');setError('')}}}><div className={'dialog '+(modal==='receipt'?'receipt-dialog':'')}><div className="dialog-head"><div><p className="eyebrow">FEE MANAGER</p><h2>{({'student':draft.id?'Edit student':'Add student','batch':draft.id?'Edit batch':'Add batch','fee':'Create monthly fee','payment':'Record payment','profile':'Student profile','batchView':'Batch details','receipt':'Payment receipt','reminder':'WhatsApp reminder'} as Rec)[modal]}</h2></div><button className="close" onClick={()=>{setModal('');setError('')}}>×</button></div>{error&&<p className="error" role="alert">{error}</p>}
{['student','batch','fee','payment'].includes(modal)&&<form onSubmit={save} className="form-grid">
{modal==='batch'&&<><Field label="Batch name" value={draft.name} update={v=>setDraft({...draft,name:v})}/><Field label="Course name" value={draft.courseName} update={v=>setDraft({...draft,courseName:v})}/><Field label="Teacher name" value={draft.teacherName} update={v=>setDraft({...draft,teacherName:v})}/><Field label="Timing" value={draft.timing} update={v=>setDraft({...draft,timing:v})}/><Field label="Monthly fee (₹)" type="number" value={draft.monthlyFee} update={v=>setDraft({...draft,monthlyFee:v})}/></>}
{modal==='student'&&<><Field label="Student ID" value={draft.studentId} update={v=>setDraft({...draft,studentId:v})}/><Field label="Student name" value={draft.name} update={v=>setDraft({...draft,name:v})}/><Field label="Parent name" value={draft.parentName} update={v=>setDraft({...draft,parentName:v})}/><Field label="Mobile number" type="tel" value={draft.mobile} update={v=>setDraft({...draft,mobile:v})}/><label>Batch<select required value={draft.batchId||''} onChange={e=>setDraft({...draft,batchId:e.target.value})}><option value="">Choose batch</option>{batches.filter(b=>b.status==='Active'||b.id===draft.batchId).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><Field label="Monthly fee (₹)" type="number" value={draft.monthlyFee} update={v=>setDraft({...draft,monthlyFee:v})}/><Field label="Joining date" type="date" value={draft.joiningDate} update={v=>setDraft({...draft,joiningDate:v})}/></>}
{modal==='fee'&&<><label>Student<select required value={draft.studentId||''} onChange={e=>{const s=students.find(s=>s.id===e.target.value);setDraft({...draft,studentId:e.target.value,totalFee:s?.monthlyFee/100})}}><option value="">Choose student</option>{students.filter(s=>s.status==='Active').map(s=><option key={s.id} value={s.id}>{s.name} ({s.studentId})</option>)}</select></label><Field label="Fee month" type="month" value={draft.month} update={v=>setDraft({...draft,month:v})}/><Field label="Total fee (₹)" type="number" value={draft.totalFee} update={v=>setDraft({...draft,totalFee:v})}/><Field label="Due date" type="date" value={draft.dueDate} update={v=>setDraft({...draft,dueDate:v})}/></>}
{modal==='payment'&&<><label>Student<select required value={draft.studentId||''} onChange={e=>setDraft({...draft,studentId:e.target.value,feeId:''})}><option value="">Choose student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} ({s.studentId})</option>)}</select></label><label>Fee month<select required value={draft.feeId||''} onChange={e=>setDraft({...draft,feeId:e.target.value})}><option value="">Choose fee</option>{fees.filter(f=>f.studentId===draft.studentId&&f.pendingAmount>0).map(f=><option key={f.id} value={f.id}>{f.month} · {money(f.pendingAmount)} due</option>)}</select></label><Field label="Amount (₹)" type="number" value={draft.amount} update={v=>setDraft({...draft,amount:v})}/><Field label="Payment date" type="date" value={draft.paymentDate||today()} update={v=>setDraft({...draft,paymentDate:v})}/><label>Payment mode<select value={draft.mode||'Cash'} onChange={e=>setDraft({...draft,mode:e.target.value})}><option>Cash</option><option>UPI</option><option>Bank Transfer</option></select></label><Field label="Notes" required={false} value={draft.notes} update={v=>setDraft({...draft,notes:v})}/></>}
<div className="form-actions"><button type="button" className="secondary" onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':modal==='payment'?'Record payment':'Save'}</button></div></form>}
{modal==='profile'&&<div className="detail"><div className="detail-grid"><Info label="Student ID" value={draft.studentId}/><Info label="Student name" value={draft.name}/><Info label="Parent name" value={draft.parentName}/><Info label="Mobile" value={draft.mobile}/><Info label="Batch" value={draft.batch?.name}/><Info label="Monthly fee" value={money(draft.monthlyFee*100)}/><Info label="Joining date" value={draft.joiningDate}/><Info label="Status" value={draft.status}/><Info label="Pending amount" value={money(draft.pendingAmount)}/></div><h3>Payment history</h3>{payments.filter(p=>p.studentId===draft.id).map(p=><div key={p.id} className="detail-row"><span>{p.fee.month} · {date(p.paymentDate)} · {p.mode}</span><strong>{money(p.amount)}</strong></div>)}{!payments.some(p=>p.studentId===draft.id)&&<p className="muted">No payments yet.</p>}</div>}
{modal==='batchView'&&<div className="detail"><div className="detail-grid"><Info label="Batch" value={draft.name}/><Info label="Course" value={draft.courseName}/><Info label="Teacher" value={draft.teacherName}/><Info label="Timing" value={draft.timing}/><Info label="Monthly fee" value={money(draft.monthlyFee*100)}/><Info label="Status" value={draft.status}/></div><h3>Students in batch</h3>{students.filter(s=>s.batchId===draft.id).map(s=><div className="detail-row" key={s.id}><span>{s.name} · {s.studentId}</span><Badge status={s.status}/></div>)}{!students.some(s=>s.batchId===draft.id)&&<p className="muted">No students assigned.</p>}</div>}
{modal==='reminder'&&<div className="detail"><p className="muted">Ready to copy. This does not send a WhatsApp message.</p><textarea rows={9} readOnly value={reminder}/><div className="form-actions"><button className="secondary" onClick={()=>setModal('')}>Cancel</button><button className="primary" onClick={copyReminder}>Copy message</button></div></div>}
{modal==='receipt'&&receipt&&<div className="receipt"><div className="receipt-brand"><div className="brand-icon">₹</div><div><h2>{receipt.instituteName}</h2><p>Payment receipt</p></div></div><div className="receipt-no">{receipt.number}</div><div className="detail-grid"><Info label="Student" value={receipt.payment.student.name}/><Info label="Student ID" value={receipt.payment.student.studentId}/><Info label="Fee month" value={receipt.payment.fee.month}/><Info label="Payment date" value={date(receipt.payment.paymentDate)}/><Info label="Payment mode" value={receipt.payment.mode}/><Info label="Remaining amount" value={money(receipt.remainingAmount)}/></div><div className="receipt-total"><span>Amount paid</span><strong>{money(receipt.payment.amount)}</strong></div><div className="form-actions no-print"><button className="secondary" onClick={()=>window.print()}>Print receipt</button><button className="primary" onClick={receiptPdf}>Download PDF</button></div></div>}
</div></div>}
</div>}
function Field({label,value,update,type='text',required=true}:{label:string,value:any,update:(v:string)=>void,type?:string,required?:boolean}){return <label>{label}<input required={required} type={type} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} value={value??''} onChange={e=>update(e.target.value)}/></label>}
function Info({label,value}:{label:string,value:any}){return <div><small>{label}</small><strong>{value||'—'}</strong></div>}
function Empty({message}:{message:string}){return <p className="empty">{message}</p>}
function Filter({search,setSearch,batch,setBatch,batches}:{search:string,setSearch:(s:string)=>void,batch:string,setBatch:(s:string)=>void,batches:Rec[]}){return <div className="filters"><input aria-label="Search student" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, ID, mobile"/><select aria-label="Filter by batch" value={batch} onChange={e=>setBatch(e.target.value)}><option value="">All batches</option>{batches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>}
