import {NextResponse} from 'next/server';
import {googleAccess,sameOrigin,sessionCookie,unseal,token,clientId,tokenClient} from '@/lib/google';
import {db,schema,isOwner} from '@/lib/db';
async function deleteSheet(sheetId:string,refreshCipher:string){const payload=unseal<{refresh:string}>(refreshCipher);if(!payload?.refresh)throw Error('Google permission unavailable');const t=await token(new URLSearchParams({client_id:clientId(),client_secret:tokenClient(),grant_type:'refresh_token',refresh_token:payload.refresh}));const headers={Authorization:`Bearer ${t.access_token}`};const query=new URLSearchParams({q:"name = 'Coaching Fee Manager Data' and mimeType = 'application/vnd.google-apps.spreadsheet' and trashed = false",fields:'nextPageToken,files(id,name)',pageSize:'100'});const ids=new Set<string>([sheetId]);let pageToken:string|undefined;do{const url='https://www.googleapis.com/drive/v3/files?'+query+(pageToken?'&pageToken='+encodeURIComponent(pageToken):'');const list=await fetch(url,{headers,cache:'no-store'});if(!list.ok)throw Error(`Cannot verify Google Sheet list (${list.status})`);const data=await list.json();for(const f of data.files||[])if(f.id)ids.add(f.id);pageToken=data.nextPageToken}while(pageToken);for(const id of ids){const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}`,{method:'DELETE',headers});if(!response.ok&&response.status!==404)throw Error(`Google Drive deletion failed (${response.status})`)}let verifyPage:string|undefined;do{const verify=await fetch('https://www.googleapis.com/drive/v3/files?'+query+(verifyPage?'&pageToken='+encodeURIComponent(verifyPage):''),{headers,cache:'no-store'});if(!verify.ok)throw Error('Could not verify Google Sheet deletion');const remaining=await verify.json();if((remaining.files||[]).length)throw Error('Could not verify all app-created Sheets were removed');verifyPage=remaining.nextPageToken}while(verifyPage)}
async function remove(sub:string,actor:string){await schema();const sql=db();const [row]=await sql`SELECT sheet_id,refresh_cipher,deleted_at FROM tenants WHERE sub=${sub}`;if(!row)return {ok:false,error:'Account not found'};if(row.sheet_id&&!row.refresh_cipher)return {ok:false,error:'Customer Google access unavailable; cannot delete their Sheet. No records removed.'};
// A failed Google request leaves private data inaccessible but retained for a supervised retry.
await sql`UPDATE tenants SET deleted_at=COALESCE(deleted_at,now()),suspended=true WHERE sub=${sub}`;
try{if(row.sheet_id)await deleteSheet(row.sheet_id,row.refresh_cipher);await sql.begin(async tx=>{await tx`INSERT INTO admin_audit(actor_sub,target_sub,action) VALUES(${actor},${sub},'account_deleted')`;await tx`DELETE FROM subscriptions WHERE tenant_sub=${sub}`;await tx`DELETE FROM tenants WHERE sub=${sub}`});return {ok:true}}
catch(e){await sql`UPDATE tenants SET mirror_error=${e instanceof Error?e.message.slice(0,180):'Deletion failed'} WHERE sub=${sub}`;return {ok:false,error:'Could not confirm Google Sheet deletion. Account access blocked; private records retained pending manual retry.'}}}
export async function POST(request:Request){if(!sameOrigin(request))return NextResponse.json({error:'Invalid origin'},{status:403});const a=await googleAccess();if(!a)return NextResponse.json({error:'Not signed in'},{status:401});let b:{sub?:string;confirm?:string;admin?:boolean};try{b=await request.json()}catch{return NextResponse.json({error:'Invalid request'},{status:400})}const owner=b.admin?await isOwner(a.session.sub,a.session.email):false;const sub=owner?b.sub:a.session.sub;if(!sub||b.confirm!==`DELETE ${sub}`||owner&&sub===a.session.sub)return NextResponse.json({error:'Type the exact account confirmation'},{status:400});if(b.admin&&!owner)return NextResponse.json({error:'Admin access required'},{status:403});const result=await remove(sub,a.session.sub);const response=NextResponse.json(result,{status:result.ok?200:409});if(result.ok&&sub===a.session.sub)response.cookies.delete(sessionCookie);return response}
