import {jsPDF} from 'jspdf';
type Row=Record<string,any>;
export function attendanceReportRows(students:Row[],marks:Row[],batchId:string,period:string,monthly=false){
 if(!batchId)throw Error('Choose a batch before exporting attendance');
 const days=monthly?new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate():1;
 return students.filter(s=>(s.batchIds||[s.batchId]).includes(batchId)).map(s=>{const found=marks.filter(a=>a.studentId===s.id&&a.batchId===batchId&&(monthly?String(a.date).slice(0,7)===period:String(a.date).slice(0,10)===period));const unique=new Map(found.map(a=>[String(a.date).slice(0,10),a.status]));const p=[...unique.values()].filter(v=>v==='Present').length,a=[...unique.values()].filter(v=>v==='Absent').length;return {id:s.studentId,name:s.name,present:p,absent:a,marked:p+a,unmarked:Math.max(0,days-p-a),rate:p+a?100*p/(p+a):null,status:unique.size?Array.from(unique.values())[0]:'Not marked',calendarDays:days};});
}
export function createAttendancePdf(students:Row[],marks:Row[],batchId:string,batchName:string,period:string,institute:string,monthly=false,images:Record<string,string>={}){const rows=attendanceReportRows(students,marks,batchId,period,monthly),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});let y=0,page=0;
 const text=(value:string,x:number,y:number,width:number)=>{if(images[value])doc.addImage(images[value],'PNG',x,y-4,width,6);else doc.text(doc.splitTextToSize(value,width)[0]||'',x,y)};
 const header=()=>{page++;doc.setTextColor(37,31,33);doc.setFontSize(17);text(institute||'Your Coaching',14,16,180);doc.setFontSize(12);doc.text((monthly?'Monthly':'Date')+' attendance | '+period+' | ',14,25);text(batchName,115,25,160);doc.setFontSize(8);doc.text('Current enrolled roster, including inactive students. No records deleted. Page '+page,14,32);doc.text(monthly?'Rate = Present / (Present + Absent). Unmarked calendar days are NOT absent; class schedule is not configured.':'One selected batch/date. Not marked is separate from Absent.',14,38);y=49;doc.setFillColor(235,241,239);doc.rect(14,y-6,269,9,'F');doc.setFontSize(9);doc.text('Student ID',16,y);doc.text('Student',49,y);if(monthly){doc.text('Present',128,y);doc.text('Absent',149,y);doc.text('Unmarked',170,y);doc.text('Rate / marked',200,y);doc.text('P / A / unmarked',240,y)}else doc.text('Status',200,y);y+=10};
 header();for(const r of rows){if(y>184){doc.addPage();header()}doc.setFontSize(9);doc.setTextColor(37,31,33);text(String(r.id),16,y,30);text(String(r.name),49,y,73);if(monthly){doc.text(String(r.present),128,y);doc.text(String(r.absent),149,y);doc.text(String(r.unmarked),170,y);doc.text(r.rate==null?'No marks':r.rate.toFixed(2)+'% / '+r.marked,200,y);let x=240;for(const [v,c] of [[r.present,[115,168,154]],[r.absent,[88,82,84]],[r.unmarked,[234,233,234]]] as [number,number[]][]){const w=40*v/r.calendarDays;doc.setFillColor(c[0],c[1],c[2]);doc.rect(x,y-4,w,5,'F');x+=w}}else doc.text(String(r.status),200,y);doc.setDrawColor(234,233,234);doc.line(14,y+3,283,y+3);y+=9}if(!rows.length)doc.text('No students enrolled in this batch.',16,y);return doc;}
