import {googleAccess,withSession,Session} from './google';
import {NextResponse} from 'next/server';
import {dateOnly,feeStatus,monthValid,toPaise} from './core';
import {randomUUID} from 'node:crypto';

type Row=Record<string,any>;
type State={version:1;batches:Row[];students:Row[];fees:Row[];payments:Row[];receipts:Row[];expenses?:Row[];attendance?:Row[];profile?:{photo:string}};
const blank=():State=>({version:1,batches:[],students:[],fees:[],payments:[],receipts:[],expenses:[],attendance:[]});
const title='Coaching Fee Manager Data';
const esc=(s:string)=>s.replaceAll("'","\\'");
async function request(access:string,url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${access}`,...init.headers},cache:'no-store'});if(!r.ok){const text=await r.text();throw Error(`Google storage error (${r.status}): ${text.slice(0,180)}`)}return r.json()}
const pendingSheets=new Map<string,Promise<string>>();
async function resolveSheetId(access:string){const q=new URLSearchParams({q:`name = '${esc(title)}' and mimeType = 'application/vnd.google-apps.spreadsheet' and trashed = false`,fields:'files(id,name,createdTime),nextPageToken',orderBy:'createdTime',pageSize:'100'});const found=await request(access,'https://www.googleapis.com/drive/v3/files?'+q);if(found.files?.length)return found.files[0].id as string;
 const created=await request(access,'https://sheets.googleapis.com/v4/spreadsheets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({properties:{title},sheets:[{properties:{title:'Records'}}]})});return created.spreadsheetId as string}
async function sheetId(access:string){let pending=pendingSheets.get(access);if(!pending){pending=resolveSheetId(access);pendingSheets.set(access,pending);pending.finally(()=>{if(pendingSheets.get(access)===pending)pendingSheets.delete(access)}).catch(()=>{});}return pending}
async function load(access:string){const id=await sheetId(access);const u=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/Records!A1:ZZ1`;const got=await request(access,u);const cells=got.values?.[0]||[];if(!cells.length)return {id,state:blank(),oldCount:0};const count=Number(cells[0]);if(!Number.isSafeInteger(count)||count<1||count>700||cells.length<count+1)throw Error('Data format mismatch. No changes were saved.');const data=JSON.parse(cells.slice(1,count+1).join(''));if(data.version!==1||!['batches','students','fees','payments','receipts'].every(k=>Array.isArray(data[k])))throw Error('Data format mismatch. No changes were saved.');data.expenses ||= [];data.attendance ||= [];return {id,state:data as State,oldCount:count}}
async function save(access:string,id:string,state:State,oldCount:number){const json=JSON.stringify(state),chunks=json.match(/[\s\S]{1,30000}/g)||[];if(chunks.length>700)throw Error('Spreadsheet capacity reached; export data before adding more records');const values=[String(chunks.length),...chunks,...Array(Math.max(0,oldCount-chunks.length)).fill('')];const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/Records!A1?valueInputOption=RAW`;await request(access,url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({range:'Records!A1',majorDimension:'ROWS',values:[values]})})}
function checkedPhoto(value:unknown){if(value==null||value==='')return '';if(typeof value!=='string'||value.length>350000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(value))throw Error('Photo must be JPEG, PNG or WebP under 250 KB');return value}
function required(value:unknown,limit=150){const s=String(value??'').trim();if(!s||s.length>limit)throw Error(`Required text must be 1-${limit} characters`);return s}
function date(v:unknown){return dateOnly(required(v,10)).toISOString()}
function batch(s:State,id:string){return s.batches.find(b=>b.id===id)}
function student(s:State,id:string){return s.students.find(st=>st.id===id)}
function fee(s:State,id:string){return s.fees.find(f=>f.id===id)}
function payment(s:State,id:string){return s.payments.find(p=>p.id===id)}
function shapedFee(s:State,f:Row):Row{const st=student(s,f.studentId),payments=s.payments.filter(p=>p.feeId===f.id).map(p=>({...p,receipt:s.receipts.find(r=>r.paymentId===p.id)} as Row)).sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate));const paid=payments.reduce((sum,p)=>sum+p.amount,0);return {...f,student:{...st,batch:batch(s,st?.batchId)},payments,paidAmount:paid,pendingAmount:Math.max(0,f.totalFee-paid),status:feeStatus(f.totalFee,paid,new Date(f.dueDate))}}
function shapedStudent(s:State,st:Row){const fees=s.fees.filter(f=>f.studentId===st.id).map(f=>shapedFee(s,f));return {...st,batch:batch(s,st.batchId),fees,pendingAmount:fees.reduce((sum,f)=>sum+f.pendingAmount,0)}}
function shapedPayment(s:State,p:Row):Row{return {...p,student:student(s,p.studentId),fee:fee(s,p.feeId),receipt:s.receipts.find(r=>r.paymentId===p.id)}}
function output(s:State,resource:string,url:URL){if(resource==='export')return s;if(resource==='expenses')return [...(s.expenses||[])].reverse();if(resource==='attendance')return s.attendance||[];if(resource==='profile')return {photo:s.profile?.photo||''};if(resource==='batches')return s.batches.map(b=>({...b,_count:{students:s.students.filter(st=>st.batchId===b.id).length}})).reverse();if(resource==='students'){const q=(url.searchParams.get('q')||'').toLowerCase(),bid=url.searchParams.get('batch');return s.students.filter(st=>(!bid||st.batchId===bid)&&(!q||[st.name,st.studentId,st.mobile].some(v=>v.toLowerCase().includes(q)))).map(st=>shapedStudent(s,st)).reverse()}if(resource==='fees')return s.fees.map(f=>shapedFee(s,f)).sort((a,b)=>b.dueDate.localeCompare(a.dueDate));if(resource==='payments')return s.payments.map(p=>shapedPayment(s,p)).sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate)||b.createdAt.localeCompare(a.createdAt));if(resource==='summary'){const fees=s.fees.map(f=>shapedFee(s,f)),payments=s.payments.map(p=>shapedPayment(s,p));const month=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}).slice(0,7);const expenses=(s.expenses||[]).filter(e=>e.date.slice(0,7)===month).reduce((sum,e)=>sum+e.amount,0);const collection=payments.filter(p=>p.paymentDate.slice(0,7)===month).reduce((sum,p)=>sum+p.amount,0);return {expenses,profit:collection-expenses,students:s.students.length,batches:s.batches.length,collection,pending:fees.reduce((sum,f)=>sum+f.pendingAmount,0),overdue:fees.filter(f=>f.status==='Overdue').reduce((sum,f)=>sum+f.pendingAmount,0),recentPayments:payments.sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate)).slice(0,8),pendingFees:fees.filter(f=>f.pendingAmount>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,8)}}throw Error('Unknown resource')}
export function validateBackup(raw:unknown):State {
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Invalid backup file');
 const x=raw as Row;if(x.version!==1)throw Error('Unsupported backup version');
 const fields=['batches','students','fees','payments','receipts','expenses','attendance'] as const;
 for(const name of fields){if(name in x&&!Array.isArray(x[name]))throw Error(`Invalid ${name} in backup`)}
 for(const name of fields.slice(0,5)){if(!Array.isArray(x[name]))throw Error(`Missing ${name} in backup`)}
 const state:State={version:1,batches:x.batches,students:x.students,fees:x.fees,payments:x.payments,receipts:x.receipts,expenses:x.expenses||[],attendance:x.attendance||[],profile:{photo:checkedPhoto(x.profile?.photo)}};
 const json=JSON.stringify(state);if(json.length>18_000_000)throw Error('Backup exceeds safe spreadsheet capacity');
 const ids=new Set<string>();for(const name of fields){if(state[name]!.length>10000)throw Error(`Too many ${name} records`);for(const row of state[name]!){if(!row||typeof row!=='object'||Array.isArray(row)||typeof row.id!=='string'||!row.id||ids.has(row.id))throw Error(`Invalid or repeated ID in ${name}`);ids.add(row.id)}}
 const has=(name:typeof fields[number],id:unknown)=>typeof id==='string'&&state[name]!.some(row=>row.id===id);
 const str=(v:unknown,max=250)=>typeof v==='string'&&v.length<=max;
 const amount=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
 const validDate=(v:unknown)=>{try{dateOnly(String(v).slice(0,10));return /^\d{4}-\d{2}-\d{2}T00:00:00\.000Z$/.test(String(v))}catch{return false}};
 for(const b of state.batches)if(!str(b.name)||!str(b.courseName)||!str(b.teacherName)||!str(b.timing)||!amount(b.monthlyFee)||!['Active','Inactive'].includes(b.status))throw Error('Invalid batch record');
 for(const st of state.students)if(!has('batches',st.batchId)||!str(st.studentId)||!str(st.name)||!str(st.parentName)||!str(st.mobile,30)||!str(st.notes||'',1000)||!amount(st.monthlyFee)||!validDate(st.joiningDate)||!['Active','Inactive'].includes(st.status))throw Error('Invalid student record');else checkedPhoto(st.photo);
 for(const f of state.fees)if(!has('students',f.studentId)||!monthValid(f.month)||!amount(f.totalFee)||!validDate(f.dueDate)||f.discount!==undefined&&(!amount(f.discount)||!amount(f.baseFee)||f.totalFee!==f.baseFee-f.discount))throw Error('Invalid fee record');
 for(const p of state.payments)if(!has('students',p.studentId)||!has('fees',p.feeId)||state.fees.find(f=>f.id===p.feeId)?.studentId!==p.studentId||!amount(p.amount)||p.amount===0||!validDate(p.paymentDate)||!['Cash','UPI','Bank Transfer'].includes(p.mode)||!str(p.notes||'',500))throw Error('Invalid payment record');
 for(const r of state.receipts)if(!has('payments',r.paymentId)||!str(r.number,80)||!amount(r.remainingAmount))throw Error('Invalid receipt record');
 if(new Set(state.receipts.map(r=>r.paymentId)).size!==state.receipts.length)throw Error('Repeated receipt payment in backup');
 for(const f of state.fees)if(state.payments.filter(p=>p.feeId===f.id).reduce((sum,p)=>sum+p.amount,0)>f.totalFee)throw Error('Payments exceed fee in backup');
 for(const e of state.expenses||[])if(!str(e.category,60)||!str(e.description,250)||!amount(e.amount)||e.amount===0||!validDate(e.date))throw Error('Invalid expense record');
 for(const a of state.attendance||[])if(!has('students',a.studentId)||!has('batches',a.batchId)||state.students.find(st=>st.id===a.studentId)?.batchId!==a.batchId||!validDate(a.date)||!['Present','Absent'].includes(a.status))throw Error('Invalid attendance record');
 return JSON.parse(json) as State;
}
function change(s:State,resource:string,method:string,b:Row){if(method==='PATCH'&&resource==='profile'){const photo=b.photo;if(typeof photo!=='string'||(photo!==''&&(!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(photo)||photo.length>350000)))throw Error('Choose a JPEG, PNG or WebP photo under 250 KB after resizing');s.profile={photo};return {photo}}const now=new Date().toISOString();if(method==='POST'){
 if(resource==='import')throw Error('Import uses the dedicated restore endpoint');
 if(resource==='expenses'){const v={id:randomUUID(),category:required(b.category,60),description:required(b.description,250),amount:toPaise(b.amount),date:date(b.date),createdAt:now};if(v.amount<=0)throw Error('Expense must be greater than zero');(s.expenses ||= []).push(v);return v}
 if(resource==='attendance'){const st=student(s,b.studentId);if(!st||st.batchId!==b.batchId)throw Error('Student does not belong to batch');const day=date(b.date);if(!['Present','Absent'].includes(b.status))throw Error('Invalid attendance status');const arr=s.attendance ||= [];const old=arr.find(x=>x.studentId===st.id&&x.date===day);if(old){old.status=b.status;return old}const v={id:randomUUID(),studentId:st.id,batchId:st.batchId,date:day,status:b.status};arr.push(v);return v}

 if(resource==='batches'){const name=required(b.name);if(s.batches.some(x=>x.name.toLowerCase()===name.toLowerCase()))throw Error('Batch name already exists');const v={id:randomUUID(),name,courseName:required(b.courseName),teacherName:required(b.teacherName),timing:required(b.timing),monthlyFee:toPaise(b.monthlyFee),status:'Active',createdAt:now};s.batches.push(v);return v}
 if(resource==='students'){const studentId=required(b.studentId,60);if(s.students.some(x=>x.studentId.toLowerCase()===studentId.toLowerCase()))throw Error('Student ID already exists');if(batch(s,b.batchId)?.status!=='Active')throw Error('Choose an active batch');const v={id:randomUUID(),studentId,name:required(b.name),parentName:required(b.parentName),mobile:required(b.mobile,30),batchId:b.batchId,monthlyFee:toPaise(b.monthlyFee),joiningDate:date(b.joiningDate),notes:String(b.notes||'').slice(0,1000),photo:checkedPhoto(b.photo),status:'Active',createdAt:now};s.students.push(v);return v}
 if(resource==='fees'){if(!monthValid(b.month))throw Error('Fee month must be YYYY-MM');if(student(s,b.studentId)?.status!=='Active')throw Error('Choose an active student');if(s.fees.some(x=>x.studentId===b.studentId&&x.month===b.month))throw Error('Fee already exists for that month');const baseFee=toPaise(b.totalFee),discount=toPaise(b.discount||0);if(discount>baseFee)throw Error('Discount exceeds fee');const v={id:randomUUID(),studentId:b.studentId,month:b.month,baseFee,discount,totalFee:baseFee-discount,dueDate:date(b.dueDate)};s.fees.push(v);return v}
 if(resource==='payments'){const amount=toPaise(b.amount);if(amount<=0)throw Error('Payment must be greater than zero');if(!['Cash','UPI','Bank Transfer'].includes(b.mode))throw Error('Invalid payment mode');const f=fee(s,b.feeId);if(!f)throw Error('Fee not found');const paid=s.payments.filter(p=>p.feeId===f.id).reduce((sum,p)=>sum+p.amount,0);if(amount>f.totalFee-paid)throw Error('Payment exceeds pending amount');const v={id:randomUUID(),studentId:f.studentId,feeId:f.id,amount,paymentDate:date(b.paymentDate),mode:b.mode,notes:String(b.notes||'').slice(0,500),createdAt:now};const receipt={id:randomUUID(),paymentId:v.id,number:`REC-${String(s.receipts.length+1).padStart(5,'0')}`,remainingAmount:f.totalFee-paid-amount,createdAt:now};s.payments.push(v);s.receipts.push(receipt);return {...v,receipt}}
 }
 if(method==='PATCH'&&['students','batches'].includes(resource)){const arr=resource==='students'?s.students:s.batches;const v=arr.find(x=>x.id===b.id);if(!v)throw Error('Record not found');if(b.status&&b.status!==v.status){if(!['Active','Inactive'].includes(b.status))throw Error('Invalid status');v.status=b.status;return v}if(resource==='students'){const studentId=required(b.studentId,60);if(s.students.some(x=>x.id!==v.id&&x.studentId.toLowerCase()===studentId.toLowerCase()))throw Error('Student ID already exists');if(batch(s,b.batchId)?.status!=='Active')throw Error('Choose an active batch');Object.assign(v,{studentId,name:required(b.name),parentName:required(b.parentName),mobile:required(b.mobile,30),batchId:b.batchId,monthlyFee:toPaise(b.monthlyFee),joiningDate:date(b.joiningDate),notes:String(b.notes||'').slice(0,1000),photo:checkedPhoto(b.photo)})}else{const name=required(b.name);if(s.batches.some(x=>x.id!==v.id&&x.name.toLowerCase()===name.toLowerCase()))throw Error('Batch name already exists');Object.assign(v,{name,courseName:required(b.courseName),teacherName:required(b.teacherName),timing:required(b.timing),monthlyFee:toPaise(b.monthlyFee)})}return v}
 throw Error('Cannot edit financial records')}
export function receipt(s:State,id:string){const r=s.receipts.find(x=>x.id===id);if(!r)return null;const p=payment(s,r.paymentId);if(!p)return null;return {...r,payment:shapedPayment(s,p),instituteName:process.env.INSTITUTE_NAME||'ABC Coaching'}}
export async function access(){return googleAccess()}
export async function readStore(a:NonNullable<Awaited<ReturnType<typeof googleAccess>>>){const {state}=await load(a.access);return state}
export function getResult(s:State,resource:string,url:URL){return output(s,resource,url)}
// A single Node instance serializes writes, but Sheets does not offer a multi-instance atomic compare-and-swap.
let queue=Promise.resolve();export async function mutate(a:NonNullable<Awaited<ReturnType<typeof googleAccess>>>,resource:string,method:string,b:Row){const run=async()=>{const {state,id,oldCount}=await load(a.access);const result=change(state,resource,method,b);await save(a.access,id,state,oldCount);return result};const next=queue.then(run,run);queue=next.then(()=>{},()=>{});return next}
export async function restore(a:NonNullable<Awaited<ReturnType<typeof googleAccess>>>,raw:unknown){const replacement=validateBackup(raw);const run=async()=>{const {id,oldCount}=await load(a.access);await save(a.access,id,replacement,oldCount);return {batches:replacement.batches.length,students:replacement.students.length,fees:replacement.fees.length,payments:replacement.payments.length}};const next=queue.then(run,run);queue=next.then(()=>{},()=>{});return next}
export {withSession};
