import {googleAccess,withSession,Session} from './google';
import {NextResponse} from 'next/server';
import {dateOnly,feeStatus,monthValid,toPaise} from './core';
import {randomUUID} from 'node:crypto';

type Row=Record<string,any>;
type State={version:1;batches:Row[];students:Row[];fees:Row[];payments:Row[];receipts:Row[]};
const blank=():State=>({version:1,batches:[],students:[],fees:[],payments:[],receipts:[]});
const title='Coaching Fee Manager Data';
const esc=(s:string)=>s.replaceAll("'","\\'");
async function request(access:string,url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${access}`,...init.headers},cache:'no-store'});if(!r.ok){const text=await r.text();throw Error(`Google storage error (${r.status}): ${text.slice(0,180)}`)}return r.json()}
const pendingSheets=new Map<string,Promise<string>>();
async function resolveSheetId(access:string){const q=new URLSearchParams({q:`name = '${esc(title)}' and mimeType = 'application/vnd.google-apps.spreadsheet' and trashed = false`,fields:'files(id,name,createdTime),nextPageToken',orderBy:'createdTime',pageSize:'100'});const found=await request(access,'https://www.googleapis.com/drive/v3/files?'+q);if(found.files?.length)return found.files[0].id as string;
 const created=await request(access,'https://sheets.googleapis.com/v4/spreadsheets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({properties:{title},sheets:[{properties:{title:'Records'}}]})});return created.spreadsheetId as string}
async function sheetId(access:string){let pending=pendingSheets.get(access);if(!pending){pending=resolveSheetId(access);pendingSheets.set(access,pending);pending.finally(()=>{if(pendingSheets.get(access)===pending)pendingSheets.delete(access)}).catch(()=>{});}return pending}
async function load(access:string){const id=await sheetId(access);const u=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/Records!A1:ZZ1`;const got=await request(access,u);const cells=got.values?.[0]||[];if(!cells.length)return {id,state:blank(),oldCount:0};const count=Number(cells[0]);if(!Number.isSafeInteger(count)||count<1||count>700||cells.length<count+1)throw Error('Data format mismatch. No changes were saved.');const data=JSON.parse(cells.slice(1,count+1).join(''));if(data.version!==1||!['batches','students','fees','payments','receipts'].every(k=>Array.isArray(data[k])))throw Error('Data format mismatch. No changes were saved.');return {id,state:data as State,oldCount:count}}
async function save(access:string,id:string,state:State,oldCount:number){const json=JSON.stringify(state),chunks=json.match(/[\s\S]{1,30000}/g)||[];if(chunks.length>700)throw Error('Spreadsheet capacity reached; export data before adding more records');const values=[String(chunks.length),...chunks,...Array(Math.max(0,oldCount-chunks.length)).fill('')];const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/Records!A1?valueInputOption=RAW`;await request(access,url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({range:'Records!A1',majorDimension:'ROWS',values:[values]})})}
function required(value:unknown,limit=150){const s=String(value??'').trim();if(!s||s.length>limit)throw Error(`Required text must be 1-${limit} characters`);return s}
function date(v:unknown){return dateOnly(required(v,10)).toISOString()}
function batch(s:State,id:string){return s.batches.find(b=>b.id===id)}
function student(s:State,id:string){return s.students.find(st=>st.id===id)}
function fee(s:State,id:string){return s.fees.find(f=>f.id===id)}
function payment(s:State,id:string){return s.payments.find(p=>p.id===id)}
function shapedFee(s:State,f:Row):Row{const st=student(s,f.studentId),payments=s.payments.filter(p=>p.feeId===f.id).map(p=>({...p,receipt:s.receipts.find(r=>r.paymentId===p.id)} as Row)).sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate));const paid=payments.reduce((sum,p)=>sum+p.amount,0);return {...f,student:{...st,batch:batch(s,st?.batchId)},payments,paidAmount:paid,pendingAmount:Math.max(0,f.totalFee-paid),status:feeStatus(f.totalFee,paid,new Date(f.dueDate))}}
function shapedStudent(s:State,st:Row){const fees=s.fees.filter(f=>f.studentId===st.id).map(f=>shapedFee(s,f));return {...st,batch:batch(s,st.batchId),fees,pendingAmount:fees.reduce((sum,f)=>sum+f.pendingAmount,0)}}
function shapedPayment(s:State,p:Row):Row{return {...p,student:student(s,p.studentId),fee:fee(s,p.feeId),receipt:s.receipts.find(r=>r.paymentId===p.id)}}
function output(s:State,resource:string,url:URL){if(resource==='batches')return s.batches.map(b=>({...b,_count:{students:s.students.filter(st=>st.batchId===b.id).length}})).reverse();if(resource==='students'){const q=(url.searchParams.get('q')||'').toLowerCase(),bid=url.searchParams.get('batch');return s.students.filter(st=>(!bid||st.batchId===bid)&&(!q||[st.name,st.studentId,st.mobile].some(v=>v.toLowerCase().includes(q)))).map(st=>shapedStudent(s,st)).reverse()}if(resource==='fees')return s.fees.map(f=>shapedFee(s,f)).sort((a,b)=>b.dueDate.localeCompare(a.dueDate));if(resource==='payments')return s.payments.map(p=>shapedPayment(s,p)).sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate)||b.createdAt.localeCompare(a.createdAt));if(resource==='summary'){const fees=s.fees.map(f=>shapedFee(s,f)),payments=s.payments.map(p=>shapedPayment(s,p));const month=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}).slice(0,7);return {students:s.students.length,batches:s.batches.length,collection:payments.filter(p=>p.paymentDate.slice(0,7)===month).reduce((sum,p)=>sum+p.amount,0),pending:fees.reduce((sum,f)=>sum+f.pendingAmount,0),overdue:fees.filter(f=>f.status==='Overdue').reduce((sum,f)=>sum+f.pendingAmount,0),recentPayments:payments.sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate)).slice(0,8),pendingFees:fees.filter(f=>f.pendingAmount>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,8)}}throw Error('Unknown resource')}
function change(s:State,resource:string,method:string,b:Row){const now=new Date().toISOString();if(method==='POST'){
 if(resource==='batches'){const name=required(b.name);if(s.batches.some(x=>x.name.toLowerCase()===name.toLowerCase()))throw Error('Batch name already exists');const v={id:randomUUID(),name,courseName:required(b.courseName),teacherName:required(b.teacherName),timing:required(b.timing),monthlyFee:toPaise(b.monthlyFee),status:'Active',createdAt:now};s.batches.push(v);return v}
 if(resource==='students'){const studentId=required(b.studentId,60);if(s.students.some(x=>x.studentId.toLowerCase()===studentId.toLowerCase()))throw Error('Student ID already exists');if(batch(s,b.batchId)?.status!=='Active')throw Error('Choose an active batch');const v={id:randomUUID(),studentId,name:required(b.name),parentName:required(b.parentName),mobile:required(b.mobile,30),batchId:b.batchId,monthlyFee:toPaise(b.monthlyFee),joiningDate:date(b.joiningDate),status:'Active',createdAt:now};s.students.push(v);return v}
 if(resource==='fees'){if(!monthValid(b.month))throw Error('Fee month must be YYYY-MM');if(student(s,b.studentId)?.status!=='Active')throw Error('Choose an active student');if(s.fees.some(x=>x.studentId===b.studentId&&x.month===b.month))throw Error('Fee already exists for that month');const v={id:randomUUID(),studentId:b.studentId,month:b.month,totalFee:toPaise(b.totalFee),dueDate:date(b.dueDate)};s.fees.push(v);return v}
 if(resource==='payments'){const amount=toPaise(b.amount);if(amount<=0)throw Error('Payment must be greater than zero');if(!['Cash','UPI','Bank Transfer'].includes(b.mode))throw Error('Invalid payment mode');const f=fee(s,b.feeId);if(!f)throw Error('Fee not found');const paid=s.payments.filter(p=>p.feeId===f.id).reduce((sum,p)=>sum+p.amount,0);if(amount>f.totalFee-paid)throw Error('Payment exceeds pending amount');const v={id:randomUUID(),studentId:f.studentId,feeId:f.id,amount,paymentDate:date(b.paymentDate),mode:b.mode,notes:String(b.notes||'').slice(0,500),createdAt:now};const receipt={id:randomUUID(),paymentId:v.id,number:`REC-${String(s.receipts.length+1).padStart(5,'0')}`,remainingAmount:f.totalFee-paid-amount,createdAt:now};s.payments.push(v);s.receipts.push(receipt);return {...v,receipt}}
 }
 if(method==='PATCH'&&['students','batches'].includes(resource)){const arr=resource==='students'?s.students:s.batches;const v=arr.find(x=>x.id===b.id);if(!v)throw Error('Record not found');if(b.status&&b.status!==v.status){if(!['Active','Inactive'].includes(b.status))throw Error('Invalid status');v.status=b.status;return v}if(resource==='students'){const studentId=required(b.studentId,60);if(s.students.some(x=>x.id!==v.id&&x.studentId.toLowerCase()===studentId.toLowerCase()))throw Error('Student ID already exists');if(batch(s,b.batchId)?.status!=='Active')throw Error('Choose an active batch');Object.assign(v,{studentId,name:required(b.name),parentName:required(b.parentName),mobile:required(b.mobile,30),batchId:b.batchId,monthlyFee:toPaise(b.monthlyFee),joiningDate:date(b.joiningDate)})}else{const name=required(b.name);if(s.batches.some(x=>x.id!==v.id&&x.name.toLowerCase()===name.toLowerCase()))throw Error('Batch name already exists');Object.assign(v,{name,courseName:required(b.courseName),teacherName:required(b.teacherName),timing:required(b.timing),monthlyFee:toPaise(b.monthlyFee)})}return v}
 throw Error('Cannot edit financial records')}
export function receipt(s:State,id:string){const r=s.receipts.find(x=>x.id===id);if(!r)return null;const p=payment(s,r.paymentId);if(!p)return null;return {...r,payment:shapedPayment(s,p),instituteName:process.env.INSTITUTE_NAME||'ABC Coaching'}}
export async function access(){return googleAccess()}
export async function readStore(a:NonNullable<Awaited<ReturnType<typeof googleAccess>>>){const {state}=await load(a.access);return state}
export function getResult(s:State,resource:string,url:URL){return output(s,resource,url)}
// A single Node instance serializes writes, but Sheets does not offer a multi-instance atomic compare-and-swap.
let queue=Promise.resolve();export async function mutate(a:NonNullable<Awaited<ReturnType<typeof googleAccess>>>,resource:string,method:string,b:Row){const run=async()=>{const {state,id,oldCount}=await load(a.access);const result=change(state,resource,method,b);await save(a.access,id,state,oldCount);return result};const next=queue.then(run,run);queue=next.then(()=>{},()=>{});return next}
export {withSession};
