import {db} from '@/lib/db';import {guard,fail,safeError} from '@/lib/http';import {dateOnly,feeStatus,monthValid,toPaise} from '@/lib/core';import {NextResponse} from 'next/server';
const batchSelect={students:true} as const;
const studentInclude={batch:true,fees:{include:{payments:{include:{receipt:true}},student:false}}} as const;
const feeInclude={student:{include:{batch:true}},payments:{include:{receipt:true},orderBy:{paymentDate:'desc' as const}}} as const;
function shapeFee(f:any){const paid=f.payments.reduce((sum:number,p:any)=>sum+p.amount,0);return {...f,paidAmount:paid,pendingAmount:Math.max(0,f.totalFee-paid),status:feeStatus(f.totalFee,paid,f.dueDate)}}
export async function GET(request:Request,{params}:{params:Promise<{resource:string}>}){if(!await guard())return fail('Not signed in',401);const {resource}=await params;const url=new URL(request.url);try{
if(resource==='batches')return NextResponse.json(await db.batch.findMany({include:{_count:{select:{students:true}}},orderBy:{createdAt:'desc'}}));
if(resource==='students'){const q=url.searchParams.get('q')||'';const batch=url.searchParams.get('batch')||'';const rows=await db.student.findMany({where:{...(batch?{batchId:batch}:{}),...(q?{OR:[{name:{contains:q}},{studentId:{contains:q}},{mobile:{contains:q}}]}:{})},include:studentInclude,orderBy:{createdAt:'desc'}});return NextResponse.json(rows.map(s=>({...s,pendingAmount:s.fees.reduce((a,f)=>a+Math.max(0,f.totalFee-f.payments.reduce((v,p)=>v+p.amount,0)),0)})))}
if(resource==='fees'){const rows=await db.fee.findMany({include:feeInclude,orderBy:{dueDate:'desc'}});return NextResponse.json(rows.map(shapeFee))}
if(resource==='payments')return NextResponse.json(await db.payment.findMany({include:{student:true,fee:true,receipt:true},orderBy:[{paymentDate:'desc'},{createdAt:'desc'}]}));
if(resource==='summary'){const [students,batches,fees,payments]=await Promise.all([db.student.count(),db.batch.count(),db.fee.findMany({include:feeInclude}),db.payment.findMany({include:{student:true},orderBy:[{paymentDate:'desc'},{createdAt:'desc'}],take:8})]);const shaped=fees.map(shapeFee),month=new Date().toISOString().slice(0,7);const collection=await db.payment.aggregate({where:{paymentDate:{gte:new Date(`${month}-01T00:00:00.000Z`),lt:new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),1))}},_sum:{amount:true}});return NextResponse.json({students,batches,collection:collection._sum.amount||0,pending:shaped.reduce((a,f)=>a+f.pendingAmount,0),overdue:shaped.filter(f=>f.status==='Overdue').reduce((a,f)=>a+f.pendingAmount,0),recentPayments:payments,pendingFees:shaped.filter(f=>f.pendingAmount>0).sort((a,b)=>a.dueDate.getTime()-b.dueDate.getTime()).slice(0,8)})}
return fail('Unknown resource',404)}catch(e){return safeError(e)}}
export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}){if(!await guard())return fail('Not signed in',401);const {resource}=await params;try{const b=await request.json();if(resource==='batches'){if(!b.name||!b.courseName||!b.teacherName||!b.timing)return fail('Complete all batch fields');return NextResponse.json(await db.batch.create({data:{name:String(b.name).trim(),courseName:String(b.courseName).trim(),teacherName:String(b.teacherName).trim(),timing:String(b.timing).trim(),monthlyFee:toPaise(b.monthlyFee),status:'Active'}}),{status:201})}
if(resource==='students'){if(!b.studentId||!b.name||!b.parentName||!b.mobile||!b.batchId)return fail('Complete all student fields');const batch=await db.batch.findUnique({where:{id:b.batchId}});if(!batch||batch.status!=='Active')return fail('Choose an active batch');return NextResponse.json(await db.student.create({data:{studentId:String(b.studentId).trim(),name:String(b.name).trim(),parentName:String(b.parentName).trim(),mobile:String(b.mobile).trim(),batchId:b.batchId,monthlyFee:toPaise(b.monthlyFee),joiningDate:dateOnly(b.joiningDate),status:'Active'}}),{status:201})}
if(resource==='fees'){if(!monthValid(b.month))return fail('Fee month must be YYYY-MM');const student=await db.student.findUnique({where:{id:b.studentId}});if(!student||student.status!=='Active')return fail('Choose an active student');return NextResponse.json(await db.fee.create({data:{studentId:b.studentId,month:b.month,totalFee:toPaise(b.totalFee),dueDate:dateOnly(b.dueDate)}}),{status:201})}
if(resource==='payments'){const amount=toPaise(b.amount);if(amount<=0)return fail('Payment must be greater than zero');if(!['Cash','UPI','Bank Transfer'].includes(b.mode))return fail('Invalid payment mode');const result=await db.$transaction(async tx=>{const fee=await tx.fee.findUnique({where:{id:b.feeId},include:{payments:true,student:true}});if(!fee)throw Error('Fee not found');const paid=fee.payments.reduce((a,p)=>a+p.amount,0);if(amount>fee.totalFee-paid)throw Error('Payment exceeds pending amount');const payment=await tx.payment.create({data:{studentId:fee.studentId,feeId:fee.id,amount,paymentDate:dateOnly(b.paymentDate),mode:b.mode,notes:String(b.notes||'').slice(0,500)}});const receipt=await tx.receipt.create({data:{paymentId:payment.id,number:`TEMP-${payment.id}`,remainingAmount:fee.totalFee-paid-amount}});const numbered=await tx.receipt.update({where:{id:receipt.id},data:{number:`REC-${String(receipt.id).padStart(5,'0')}`}});return {...payment,receipt:numbered}});return NextResponse.json(result,{status:201})}
return fail('Unknown resource',404)}catch(e){return safeError(e)}}
export async function PATCH(request:Request,{params}:{params:Promise<{resource:string}>}){if(!await guard())return fail('Not signed in',401);const {resource}=await params;try{const b=await request.json();if(!b.id)return fail('Missing id');if(resource==='students'){const old=await db.student.findUnique({where:{id:b.id}});if(!old)return fail('Student not found',404);if(b.status&&b.status!==old.status){if(!['Active','Inactive'].includes(b.status))return fail('Invalid status');return NextResponse.json(await db.student.update({where:{id:b.id},data:{status:b.status}}))}const batch=await db.batch.findUnique({where:{id:b.batchId}});if(!batch||batch.status!=='Active')return fail('Choose an active batch');return NextResponse.json(await db.student.update({where:{id:b.id},data:{studentId:String(b.studentId).trim(),name:String(b.name).trim(),parentName:String(b.parentName).trim(),mobile:String(b.mobile).trim(),batchId:b.batchId,monthlyFee:toPaise(b.monthlyFee),joiningDate:dateOnly(b.joiningDate)}}))}
if(resource==='batches'){const old=await db.batch.findUnique({where:{id:b.id}});if(!old)return fail('Batch not found',404);if(b.status&&b.status!==old.status){if(!['Active','Inactive'].includes(b.status))return fail('Invalid status');return NextResponse.json(await db.batch.update({where:{id:b.id},data:{status:b.status}}))}return NextResponse.json(await db.batch.update({where:{id:b.id},data:{name:String(b.name).trim(),courseName:String(b.courseName).trim(),teacherName:String(b.teacherName).trim(),timing:String(b.timing).trim(),monthlyFee:toPaise(b.monthlyFee)}}))}return fail('Cannot edit financial records',405)}catch(e){return safeError(e)}}
