'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';
const steps:[string,string,string][]=[
['1. Sign in and set up','Sign in with Google. Your first visit creates "Coaching Fee Manager Data" in your own Google Drive. Reuse the same account. Tap the top circle to add a profile photo; use the moon/sun for dark mode.','Google se sign in karein. Pehli baar aapke Drive me "Coaching Fee Manager Data" Sheet banegi. Dobara wahi account use karein. Upar circle se photo, moon/sun se dark mode badlein.'],
['2. Create a batch','In Batches tap Add batch. Enter name, course, teacher, time and monthly fee, then Save.','Batches me Add batch dabayein. Naam, course, teacher, time aur monthly fee bharke Save karein.'],
['3. Add students','In Students tap Add student. Fill in ID, name, parent name, mobile, batch, fee and joining date. Photo and notes are optional. Edit a row to correct it; deactivate instead of deleting to keep payment history.','Students me Add student se ID, naam, parent, mobile, batch, fee aur joining date bharein. Photo/notes optional hain. Edit se sudharein; history rakhne ke liye Deactivate karein.'],
['4. Create monthly fees','In Fees tap Create fee. Select a student and month, then enter full fee, optional discount and due date. Owed amount is fee minus discount. One fee per student per month is allowed.','Fees me Create fee dabayein. Student, mahina, poori fee, optional discount aur due date chunein. Baki rashi fee minus discount hogi. Har student/mahine ka ek fee record hota hai.'],
['5. Record installments and receipts','Use Fees > Pay or Payments > Record payment. Enter amount, date and mode. Repeat for each installment. Open a receipt to print, download PDF or tap Share PDF. On some devices, share opens a native menu; otherwise download and attach it yourself.','Fees me Pay ya Payments me Record payment chunein. Har installment ki rashi, date aur mode alag darj karein. Receipt ko print, PDF download ya Share karein. Share na chale to PDF khud attach karein.'],
['6. Follow up on overdue fees','The Dashboard shows overdue and pending totals. Pending Fees lists unpaid records. Tap Reminder to review the text. Open WhatsApp opens a message draft for the parent number; check the recipient and message before sending yourself. Nothing sends automatically.','Dashboard par overdue aur pending dekhein. Pending Fees me Reminder se text check karein. Open WhatsApp parent ke number par draft kholta hai; number aur text verify karke khud Send dabayein.'],
['7. Expenses and reports','Expenses > Add expense records rent, salary and other costs. In Reports select a month to download CSV or PDF. Net equals received payments minus expenses; pending is separate from income.','Expenses me rent, salary aur doosre kharch darj karein. Reports me mahina chunein aur CSV/PDF download karein. Net = mili payment minus expenses; pending income me nahi jodte.'],
['8. Attendance','Choose a date and batch in Attendance. Mark each active student Present or Absent. Selecting the other status for the same day updates the mark.','Attendance me date aur batch chunein; har active student ko Present ya Absent mark karein. Usi din doosra option dabane se mark badalta hai.'],
['9. Backup and safety','Backup downloads all data as JSON. Keep it private because it contains contacts and financial records. To restore a backup, choose the JSON file in Backup and review the replace warning. Download the current data first; restore replaces it, not merges it. Avoid simultaneous edits from multiple devices. Do not add sensitive real data before testing and security review. Logout clears this browser session, not the Sheet.','Backup se saara data JSON me milega. File private rakhein; isme contacts aur financial data hai. Restore ke liye Backup me JSON file chunein. Pehle current data download karein; restore purana data replace karta hai, merge nahi. Ek saath kai devices par edit na karein. Logout browser session hatata hai, Sheet nahi.']];
export default function Guide(){const [hi,setHi]=useState(false);useEffect(()=>setHi(localStorage.getItem('fee-language')==='hi'),[]);return <main className="public-page"><div className="public-shell public-policy"><nav className="public-nav"><Link href="/home">₹ Fee Manager</Link><div><Link href="/">Open app</Link><Link href="/privacy">Privacy</Link><button className="theme" onClick={()=>{const next=!hi;setHi(next);localStorage.setItem('fee-language',next?'hi':'en')}}>{hi?'English':'हिन्दी'}</button></div></nav><h1>{hi?'Fee Manager kaise use karein':'How to use Fee Manager'}</h1><p>{hi?'Shuru se monthly report tak ye steps follow karein.':'Follow these steps from setup to monthly reports.'}</p><section className="guide-video"><h2>{hi?'Poora demo video (normal speed)':'Full demo video (normal speed)'}</h2><p>{hi?'Ye sample data ka demo hai. Koi asli student data ya message use nahi hua.':'This is a sample-data walkthrough. No real student records or messages were used.'}</p><video controls preload="metadata" playsInline poster="/video-poster.svg" aria-label="Fee Manager full demo walkthrough"><source src="/videos/fee-manager-full-guide.mp4" type="video/mp4"/>{hi?'Aapka browser video nahi dikha sakta. Neeche steps padhein.':'Your browser cannot play this video. Read the steps below.'}</video></section>{steps.map(([title,en,hindi])=><section key={title}><h2>{title}</h2><p>{hi?hindi:en}</p></section>)}<footer><Link href="/">Open app</Link> · <Link href="/privacy">Privacy policy</Link></footer></div></main>}
